import React, { createContext, useContext } from 'react';
import { Platform, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import Svg, { Circle, Path, Rect } from 'react-native-svg';
import type { Screen } from '@/shared/types/navigation';

export type { Screen };

export const C = {
  primary: '#E8453C',
  primaryDark: '#C0312A',
  primaryLight: '#FFF0F0',
  bg: '#F0F1F6',
  surface: '#FFFFFF',
  border: '#EAEAF2',
  dark: '#0F1120',
  mid: '#4A4B5C',
  muted: '#9898A8',
  success: '#16A34A',
  successLight: '#DCFCE7',
  gold: '#D97706',
  goldLight: '#FEF3C7',
  blue: '#2563EB',
  blueLight: '#DBEAFE',
  purple: '#7C3AED',
  purpleLight: '#EDE9FE',
  teal: '#0D9488',
  tealLight: '#CCFBF1',
  navy: '#1E2340',
} as const;

export const defaultProfile = {
  name: 'Harshvardhan',
  phone: '9162038214',
  email: '',
  state: 'Punjab',
  city: 'Mansa',
  pincode: '151505',
  address: 'YOUR+PC8, Green Valley',
  gstHolderName: 'Harshvardhan',
  gstNumber: 'BIBPB7675A',
  panHolderName: '',
  panNumber: '',
  dealerCode: '215548',
};

export type Profile = typeof defaultProfile;
export type SubPage =
  | null
  | 'My Redemption'
  | 'Dealer Bonus'
  | 'Transfer Points'
  | 'My Orders'
  | 'Bank Details'
  | 'Refer To A Friend'
  | 'Need Help'
  | 'Offers & Promotions'
  | 'Notifications'
  | 'Password'
  | 'App Settings'
  | 'Scan History'
  | 'Contact Support';

export type IconName =
  | 'edit' | 'eye' | 'eyeOff' | 'star' | 'scan' | 'gift' | 'redeem' | 'signOut' | 'transfer'
  | 'order' | 'bank' | 'refer' | 'help' | 'offer' | 'notification' | 'settings'
  | 'history' | 'support' | 'camera' | 'gallery' | 'phone' | 'mail' | 'building'
  | 'link' | 'message' | 'whatsapp' | 'moon' | 'warning' | 'arrowLeft' | 'check' | 'lock'
  | 'chevronRight' | 'chevronDown' | 'chevronUp' | 'location' | 'search';

export type AppLanguage = 'English' | 'Hindi' | 'Punjabi';

export const translations = {
  English: {
    myProfile: 'My Profile', edit: 'Edit', goldMember: 'Gold Member', dealerPartner: 'Dealer Partner',
    electricianPartner: 'Electrician Partner', toPlatinum: '750 pts to Platinum', scans: 'Scans',
    points: 'Points', rewards: 'Rewards', profileDetails: 'Profile Details', show: 'Show', hide: 'Hide',
    quickActions: 'Quick Actions', settings: 'Settings', giftStore: 'Gift Store', signOut: 'Logout',
    appSettings: 'App Settings', preferences: 'Preferences', pushNotifications: 'Push Notifications',
    receiveAlerts: 'Receive alerts and updates', darkMode: 'Dark Mode', switchTheme: 'Switch to dark theme',
    language: 'Language', about: 'About', privacyPolicy: 'Privacy Policy', terms: 'Terms & Conditions',
    open: 'Open', english: 'English', hindi: 'Hindi', punjabi: 'Punjabi', notification: 'Notification',
    offer: 'Offer', contactSupport: 'Contact Support', contactUs: 'Contact Us', faqs: 'FAQs',
    myOrders: 'My Order', bankDetails: 'Bank Details', referFriend: 'Refer A Friend', needHelp: 'Need Help',
    transferPoint: 'Transfer Point', redemptionHistory: 'Redemption History', scanHistory: 'Scan History',
    save: 'Save', saveChanges: 'Save Changes', discard: 'Discard', cancel: 'Cancel',
    updateProfilePhoto: 'Update Profile Photo', takePhoto: 'Take a Photo', useCamera: 'Use your camera',
    chooseGallery: 'Choose from Gallery', selectPhoto: 'Select existing photo', tapToChangePhoto: 'Tap to change photo',
    submitted: 'Submitted', incompleteForm: 'Incomplete form', fillSubjectComment: 'Please fill subject and comment before submitting.',
  },
  Hindi: {
    myProfile: 'मेरी प्रोफाइल', edit: 'एडिट', goldMember: 'गोल्ड मेंबर', dealerPartner: 'डीलर पार्टनर',
    electricianPartner: 'इलेक्ट्रीशियन पार्टनर', toPlatinum: 'प्लैटिनम तक 750 पॉइंट्स', scans: 'स्कैन',
    points: 'पॉइंट्स', rewards: 'रिवॉर्ड्स', profileDetails: 'प्रोफाइल डिटेल्स', show: 'दिखाएं', hide: 'छुपाएं',
    quickActions: 'क्विक एक्शन्स', settings: 'सेटिंग्स', giftStore: 'गिफ्ट स्टोर', signOut: 'लॉगआउट',
    appSettings: 'ऐप सेटिंग्स', preferences: 'पसंद', pushNotifications: 'पुश नोटिफिकेशन्स',
    receiveAlerts: 'अलर्ट और अपडेट प्राप्त करें', darkMode: 'डार्क मोड', switchTheme: 'डार्क थीम पर स्विच करें',
    language: 'भाषा', about: 'जानकारी', privacyPolicy: 'प्राइवेसी पॉलिसी', terms: 'नियम और शर्तें',
    open: 'खोलें', english: 'अंग्रेजी', hindi: 'हिंदी', punjabi: 'पंजाबी', notification: 'नोटिफिकेशन',
    offer: 'ऑफर', contactSupport: 'सपोर्ट सहायता', contactUs: 'संपर्क करें', faqs: 'सवाल-जवाब',
    myOrders: 'मेरे ऑर्डर', bankDetails: 'बैंक डिटेल्स', referFriend: 'दोस्त को रेफर करें', needHelp: 'मदद चाहिए',
    transferPoint: 'पॉइंट ट्रांसफर', redemptionHistory: 'रिडेम्प्शन हिस्ट्री', scanHistory: 'स्कैन हिस्ट्री',
    save: 'सेव', saveChanges: 'बदलाव सेव करें', discard: 'रद्द करें', cancel: 'कैंसल',
    updateProfilePhoto: 'प्रोफाइल फोटो अपडेट करें', takePhoto: 'फोटो लें', useCamera: 'कैमरा इस्तेमाल करें',
    chooseGallery: 'गैलरी से चुनें', selectPhoto: 'मौजूदा फोटो चुनें', tapToChangePhoto: 'फोटो बदलने के लिए टैप करें',
    submitted: 'सबमिट हो गया', incompleteForm: 'फॉर्म अधूरा है', fillSubjectComment: 'सबमिट करने से पहले विषय और टिप्पणी भरें।',
  },
  Punjabi: {
    myProfile: 'ਮੇਰੀ ਪ੍ਰੋਫਾਈਲ', edit: 'ਐਡਿਟ', goldMember: 'ਗੋਲਡ ਮੈਂਬਰ', dealerPartner: 'ਡੀਲਰ ਪਾਰਟਨਰ',
    electricianPartner: 'ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ ਪਾਰਟਨਰ', toPlatinum: 'ਪਲੈਟਿਨਮ ਲਈ 750 ਪੁਆਇੰਟ', scans: 'ਸਕੈਨ',
    points: 'ਪੁਆਇੰਟ', rewards: 'ਇਨਾਮ', profileDetails: 'ਪ੍ਰੋਫਾਈਲ ਵੇਰਵਾ', show: 'ਵੇਖਾਓ', hide: 'ਛੁਪਾਓ',
    quickActions: 'ਕੁਇਕ ਐਕਸ਼ਨ', settings: 'ਸੈਟਿੰਗਜ਼', giftStore: 'ਗਿਫਟ ਸਟੋਰ', signOut: 'ਲਾਗਆਉਟ',
    appSettings: 'ਐਪ ਸੈਟਿੰਗਜ਼', preferences: 'ਪਸੰਦਾਂ', pushNotifications: 'ਪੁਸ਼ ਨੋਟਿਫਿਕੇਸ਼ਨ',
    receiveAlerts: 'ਅਲਰਟ ਅਤੇ ਅਪਡੇਟ ਪ੍ਰਾਪਤ ਕਰੋ', darkMode: 'ਡਾਰਕ ਮੋਡ', switchTheme: 'ਡਾਰਕ ਥੀਮ ਤੇ ਜਾਓ',
    language: 'ਭਾਸ਼ਾ', about: 'ਜਾਣਕਾਰੀ', privacyPolicy: 'ਪ੍ਰਾਈਵੇਸੀ ਪਾਲਿਸੀ', terms: 'ਨਿਯਮ ਅਤੇ ਸ਼ਰਤਾਂ',
    open: 'ਖੋਲ੍ਹੋ', english: 'ਅੰਗਰੇਜ਼ੀ', hindi: 'ਹਿੰਦੀ', punjabi: 'ਪੰਜਾਬੀ', notification: 'ਨੋਟਿਫਿਕੇਸ਼ਨ',
    offer: 'ਆਫਰ', contactSupport: 'ਸਹਾਇਤਾ ਸੰਪਰਕ', contactUs: 'ਸਾਡੇ ਨਾਲ ਸੰਪਰਕ', faqs: 'ਅਕਸਰ ਪੁੱਛੇ ਸਵਾਲ',
    myOrders: 'ਮੇਰੇ ਆਰਡਰ', bankDetails: 'ਬੈਂਕ ਵੇਰਵਾ', referFriend: 'ਦੋਸਤ ਨੂੰ ਰੈਫਰ ਕਰੋ', needHelp: 'ਮਦਦ ਚਾਹੀਦੀ ਹੈ',
    transferPoint: 'ਪੁਆਇੰਟ ਟ੍ਰਾਂਸਫਰ', redemptionHistory: 'ਰਿਡੈਂਪਸ਼ਨ ਹਿਸਟਰੀ', scanHistory: 'ਸਕੈਨ ਹਿਸਟਰੀ',
    save: 'ਸੇਵ', saveChanges: 'ਬਦਲਾਅ ਸੇਵ ਕਰੋ', discard: 'ਰੱਦ ਕਰੋ', cancel: 'ਰੱਦ',
    updateProfilePhoto: 'ਪ੍ਰੋਫਾਈਲ ਫੋਟੋ ਅਪਡੇਟ ਕਰੋ', takePhoto: 'ਫੋਟੋ ਖਿੱਚੋ', useCamera: 'ਕੈਮਰਾ ਵਰਤੋ',
    chooseGallery: 'ਗੈਲਰੀ ਤੋਂ ਚੁਣੋ', selectPhoto: 'ਮੌਜੂਦਾ ਫੋਟੋ ਚੁਣੋ', tapToChangePhoto: 'ਫੋਟੋ ਬਦਲਣ ਲਈ ਟੈਪ ਕਰੋ',
    submitted: 'ਜਮ੍ਹਾਂ ਹੋ ਗਿਆ', incompleteForm: 'ਫਾਰਮ ਅਧੂਰਾ ਹੈ', fillSubjectComment: 'ਸਬਮਿਟ ਕਰਨ ਤੋਂ ਪਹਿਲਾਂ ਵਿਸ਼ਾ ਅਤੇ ਟਿੱਪਣੀ ਭਰੋ।',
  },
} as const;

export const getSafeTranslation = (language: AppLanguage, key: keyof (typeof translations)['English']) => {
  const value = translations[language][key];
  return /[Ãàâ¨]/.test(value) ? translations.English[key] : value;
};

const hasCorruptedText = (value: string) => /[Ãàâ¨ï¿½]/.test(value);

const uiText: Record<AppLanguage, Record<string, string>> = {
  English: {},
  Hindi: {
    Home: 'होम',
    Product: 'प्रोडक्ट',
    Wallet: 'वॉलेट',
    Profile: 'प्रोफाइल',
    Electricians: 'इलेक्ट्रिशियन',
    SCAN: 'स्कैन',
    Continue: 'जारी रखें',
    Login: 'लॉगिन',
    Verify: 'वेरिफाई',
    OTP: 'OTP',
    Password: 'पासवर्ड',
    Notifications: 'नोटिफिकेशन्स',
    Enter: 'दर्ज करें',
    'Create Account': 'अकाउंट बनाएं',
    'Welcome to SRV': 'SRV में आपका स्वागत है',
    'Choose your language': 'अपनी भाषा चुनें',
    'Choose your role': 'अपनी भूमिका चुनें',
    'Choose your role to start the onboarding journey.': 'ऑनबोर्डिंग शुरू करने के लिए अपनी भूमिका चुनें।',
    'Pick your preferred language first, then continue to the onboarding screen.': 'पहले अपनी पसंदीदा भाषा चुनें, फिर ऑनबोर्डिंग स्क्रीन पर आगे बढ़ें।',
    'Professional authentication flow aligned with the app design system.': 'ऐप डिजाइन सिस्टम के अनुसार प्रोफेशनल ऑथेंटिकेशन फ्लो।',
    'Language Setup': 'भाषा सेटअप',
    'Account Setup': 'अकाउंट सेटअप',
    'App Preferences': 'ऐप प्रेफरेंस',
    'CHOOSE YOUR LANGUAGE': 'अपनी भाषा चुनें',
    'Use the same language across the complete SRV app experience.': 'पूरे SRV ऐप अनुभव में एक ही भाषा का उपयोग करें।',
    'CHOOSE YOUR ROLE': 'अपनी भूमिका चुनें',
    'This keeps rewards, verification and account setup perfectly aligned.': 'इससे रिवॉर्ड, वेरिफिकेशन और अकाउंट सेटअप सही तरीके से जुड़े रहते हैं।',
    Authentication: 'ऑथेंटिकेशन',
    'Welcome back': 'वापसी पर स्वागत है',
    'Create your account': 'अपना अकाउंट बनाएं',
    'Smooth inputs, full-screen layout, and no keyboard overlap while typing.': 'स्मूद इनपुट, फुल-स्क्रीन लेआउट और टाइपिंग के दौरान बिना कीबोर्ड ओवरलैप।',
    Electrician: 'इलेक्ट्रीशियन',
    Dealer: 'डीलर',
    'Field rewards and quick verification': 'फील्ड रिवॉर्ड्स और तेज वेरिफिकेशन',
    'Business onboarding and account access': 'बिजनेस ऑनबोर्डिंग और अकाउंट एक्सेस',
    'Select Login Method': 'लॉगिन तरीका चुनें',
    'Login with OTP': 'OTP से लॉगिन',
    'Login with Password': 'पासवर्ड से लॉगिन',
    'Mobile Number': 'मोबाइल नंबर',
    'Email Address': 'ईमेल पता',
    'Enter mobile number': 'मोबाइल नंबर दर्ज करें',
    'Enter owner or business name': 'मालिक या बिजनेस का नाम दर्ज करें',
    'Enter GST or PAN number': 'GST या PAN नंबर दर्ज करें',
    'Enter holder name': 'होल्डर का नाम दर्ज करें',
    'Enter 4 digit OTP': '4 अंकों का OTP दर्ज करें',
    'Verify OTP': 'OTP वेरिफाई करें',
    'OTP sent to': 'OTP भेजा गया',
    'OTP verification successful.': 'OTP वेरिफिकेशन सफल हुआ।',
    'OTP verified successfully.': 'OTP सफलतापूर्वक वेरिफाई हुआ।',
    'Logging In...': 'लॉगिन हो रहा है...',
    'Enter password': 'पासवर्ड दर्ज करें',
    'Step 1 of 5': 'स्टेप 1 ऑफ 5',
    'Step 2 of 5': 'स्टेप 2 ऑफ 5',
    'Step 3 of 5': 'स्टेप 3 ऑफ 5',
    'Step 4 of 5': 'स्टेप 4 ऑफ 5',
    'Step 5 of 5': 'स्टेप 5 ऑफ 5',
    'Business Profile': 'बिजनेस प्रोफाइल',
    'Business Address': 'बिजनेस पता',
    'Location Details': 'लोकेशन डिटेल्स',
    'Business Identity': 'बिजनेस पहचान',
    'Mobile Verification': 'मोबाइल वेरिफिकेशन',
    'Password & Consent': 'पासवर्ड और सहमति',
    'Continue to Location': 'लोकेशन पर जारी रखें',
    'Continue to Identity': 'पहचान पर जारी रखें',
    'Continue to Mobile Verification': 'मोबाइल वेरिफिकेशन पर जारी रखें',
    'Continue to Security': 'सिक्योरिटी पर जारी रखें',
    'Enter complete business address': 'पूरा बिजनेस पता दर्ज करें',
    'Creating Account...': 'अकाउंट बनाया जा रहा है...',
    'Skip for Now': 'अभी छोड़ें',
    'Enter the owner or business name, email address, and business address in a clean business format.': 'मालिक या बिजनेस का नाम, ईमेल और बिजनेस पता सही तरीके से दर्ज करें।',
    'Review the state, city, and pincode. Auto-filled details can still be edited if needed.': 'राज्य, शहर और पिनकोड देखें। जरूरत हो तो ऑटो-फिल की गई जानकारी बदली जा सकती है।',
    'Add GST or PAN details now, or skip this step and update them later from Edit Profile.': 'अभी GST या PAN जानकारी जोड़ें, या इस स्टेप को छोड़कर बाद में Edit Profile से अपडेट करें।',
    'Verify the dealer mobile number before moving to the final security step.': 'आखिरी सिक्योरिटी स्टेप से पहले डीलर मोबाइल नंबर वेरिफाई करें।',
    'Create a password if you want and finish the account setup securely.': 'चाहें तो पासवर्ड बनाएं और अकाउंट सेटअप सुरक्षित रूप से पूरा करें।',
    'Current Address': 'वर्तमान पता',
    'Fetching current address...': 'वर्तमान पता लाया जा रहा है...',
    Locating: 'लोकेट किया जा रहा है',
    Resend: 'फिर भेजें',
    'Phone verification successful.': 'फोन वेरिफिकेशन सफल रहा।',
    'Password is optional. Leave both fields blank if you want to skip it.': 'पासवर्ड वैकल्पिक है। अगर छोड़ना चाहते हैं तो दोनों फ़ील्ड खाली छोड़ दें।',
    'Password (Optional)': 'पासवर्ड (वैकल्पिक)',
    'Confirm Password (Optional)': 'पासवर्ड की पुष्टि करें (वैकल्पिक)',
    'Create password if you want': 'चाहें तो पासवर्ड बनाएं',
    'Re-enter password': 'पासवर्ड फिर से दर्ज करें',
    'By creating an account, you agree to the Terms & Conditions and Privacy Policy.': 'अकाउंट बनाकर आप नियम और शर्तों तथा प्राइवेसी पॉलिसी से सहमत होते हैं।',
    'Full Name': 'पूरा नाम',
    'Enter your full name': 'अपना पूरा नाम दर्ज करें',
    'Dealer Verification Number': 'डीलर वेरिफिकेशन नंबर',
    'Enter dealer mobile number': 'डीलर मोबाइल नंबर दर्ज करें',
    Address: 'पता',
    'Enter your complete address': 'अपना पूरा पता दर्ज करें',
    'Detected Location Details': 'पहचानी गई लोकेशन डिटेल्स',
    State: 'राज्य',
    City: 'शहर',
    Pincode: 'पिनकोड',
    'Your Phone Number': 'आपका फोन नंबर',
    'Enter your phone number': 'अपना फोन नंबर दर्ज करें',
    Opening: 'खोला जा रहा है',
    'Scan & Earn': 'स्कैन और कमाएं',
    'Instant points': 'तुरंत पॉइंट्स',
    'Balance & history': 'बैलेंस और हिस्ट्री',
    WhatsApp: 'व्हाट्सऐप',
    'Premium support': 'प्रीमियम सपोर्ट',
    'Top Picks': 'टॉप पिक्स',
    'Featured products': 'फीचर्ड प्रोडक्ट्स',
    All: 'सभी',
    Boxes: 'बॉक्स',
    Fans: 'फैन',
    'View all': 'सभी देखें',
    'Recent Activity': 'हाल की गतिविधि',
    'Latest actions': 'ताज़ा गतिविधियां',
    'QR scanned successfully': 'QR सफलतापूर्वक स्कैन हुआ',
    'Today, 10:23 AM': 'आज, 10:23 AM',
    Yesterday: 'कल',
    '2 days ago': '2 दिन पहले',
    'Reward redeemed': 'रिवॉर्ड रिडीम हुआ',
    'Referral bonus added': 'रेफरल बोनस जोड़ा गया',
    'Total Points': 'कुल पॉइंट्स',
    'Member Tier': 'मेंबर टियर',
    'Top reward level unlocked': 'टॉप रिवॉर्ड लेवल अनलॉक हो गया',
    'Scan to Earn': 'स्कैन करके कमाएं',
    Popular: 'पॉपुलर',
    'Top Pick': 'टॉप पिक',
    'Associate Electrician': 'इलेक्ट्रीशियन जोड़ें',
    'My Redemption': 'मेरा रिडेम्प्शन',
    'Gift Store': 'गिफ्ट स्टोर',
    'Transfer Points': 'पॉइंट्स ट्रांसफर',
    'My Orders': 'मेरे ऑर्डर',
    'Bank Details': 'बैंक डिटेल्स',
    'Secure payouts to your bank': 'अपने बैंक को सुरक्षित पेआउट',
    'BANK TRANSFER': 'बैंक ट्रांसफर',
    'Account Holder Name': 'खाताधारक का नाम',
    'Enter Account Holder Name': 'खाताधारक का नाम दर्ज करें',
    'Account Number': 'खाता संख्या',
    'Enter Account Number': 'खाता संख्या दर्ज करें',
    'IFSC Code': 'IFSC कोड',
    'Enter IFSC Code': 'IFSC कोड दर्ज करें',
    'Select Bank': 'बैंक चुनें',
    'UPI ID': 'UPI ID',
    'Enter UPI ID': 'UPI ID दर्ज करें',
    'Please enter a valid UPI ID in the format name@bank.': 'कृपया name@bank फॉर्मेट में सही UPI ID दर्ज करें।',
    'Add your bank account and UPI ID for smooth payouts': 'सहज पेआउट के लिए अपना बैंक खाता और UPI ID जोड़ें',
    'Saved': 'सेव किया गया',
    'Bank details saved successfully!': 'बैंक डिटेल्स सफलतापूर्वक सेव हो गए!',
    'Required fields': 'आवश्यक फील्ड',
    'Please fill all required fields.': 'कृपया सभी आवश्यक फील्ड भरें।',
    'Invalid account holder name': 'अमान्य खाताधारक नाम',
    'Account holder name should contain only letters and spaces.': 'खाताधारक नाम में केवल अक्षर और स्पेस होने चाहिए।',
    'Invalid account number': 'अमान्य खाता संख्या',
    'Account number should contain only numbers.': 'खाता संख्या में केवल अंक होने चाहिए।',
    'Invalid UPI ID': 'अमान्य UPI ID',
    'Refer To A Friend': 'दोस्त को रेफर करें',
    'Need Help': 'मदद चाहिए',
    'Offers & Promotions': 'ऑफर्स और प्रमोशन्स',
    'App Settings': 'ऐप सेटिंग्स',
    'Scan History': 'स्कैन हिस्ट्री',
    'Contact Support': 'कॉन्टैक्ट सपोर्ट',
    connected: 'जुड़े हुए',
    contacts: 'कॉन्टैक्ट्स',
    'Open phone and WhatsApp actions': 'फोन और व्हाट्सऐप एक्शन खोलें',
    'Top dealer grade unlocked': 'टॉप डीलर ग्रेड अनलॉक हो गया',
    'Payout and history': 'पेआउट और हिस्ट्री',
    'Call Electrician': 'इलेक्ट्रीशियन को कॉल करें',
    'Reach your network': 'अपने नेटवर्क तक पहुंचें',
    'Business support': 'बिजनेस सपोर्ट',
    Catalog: 'कैटलॉग',
    'Hot Deal': 'हॉट डील',
    'Dealer Growth': 'डीलर ग्रोथ',
    'My Profile': 'मेरी प्रोफाइल',
    'Review photo': 'फोटो देखें',
    Done: 'पूरा',
    'Edit Profile': 'प्रोफाइल एडिट करें',
    'Profile Photo': 'प्रोफाइल फोटो',
    'Phone Number': 'फोन नंबर',
    Email: 'ईमेल',
    'Not provided': 'दिया नहीं गया',
    'Dealer Partner': 'डीलर पार्टनर',
    'Electrician Partner': 'इलेक्ट्रीशियन पार्टनर',
    'GST Holder Name': 'GST होल्डर नाम',
    'GST Number': 'GST नंबर',
    'PAN Holder Name': 'PAN होल्डर नाम',
    'PAN Number': 'PAN नंबर',
    'Dealer Code': 'डीलर कोड',
    'Electrician Code': 'इलेक्ट्रीशियन कोड',
    'After selecting a photo, review it and tap Done to continue.': 'फोटो चुनने के बाद उसे देखें और आगे बढ़ने के लिए अपलोड दबाएं।',
    'If the crop looks right, tap Done to update your profile photo.': 'अगर क्रॉप सही लगे तो प्रोफाइल फोटो अपडेट करने के लिए अपलोड दबाएं।',
    'Choose from camera or gallery, crop if needed, then finish with Done on the confirmation screen.': 'कैमरा या गैलरी से चुनें, फिर कन्फर्मेशन स्क्रीन पर Done दबाएं।',
    'Are you sure you want to sign out?\nYour data will be saved.': 'क्या आप वाकई लॉगआउट करना चाहते हैं?\nआपका डेटा सेव रहेगा।',
    'Invalid name': 'अमान्य नाम',
    'Name should contain only alphabets and spaces.': 'नाम में केवल अक्षर और स्पेस होने चाहिए।',
    'Invalid phone number': 'अमान्य फोन नंबर',
    'Phone number should contain only integers.': 'फोन नंबर में केवल अंक होने चाहिए।',
    'Invalid email': 'अमान्य ईमेल',
    'Please enter a valid email address.': 'कृपया सही ईमेल पता दर्ज करें।',
    'Invalid city': 'अमान्य शहर',
    'City should contain only alphabets and spaces.': 'शहर के नाम में केवल अक्षर और स्पेस होने चाहिए।',
    'Invalid state': 'अमान्य राज्य',
    'State should contain only alphabets and spaces.': 'राज्य के नाम में केवल अक्षर और स्पेस होने चाहिए।',
    'Invalid pincode': 'अमान्य पिनकोड',
    'Pincode should contain only integers.': 'पिनकोड में केवल अंक होने चाहिए।',
    'Invalid holder name': 'अमान्य होल्डर नाम',
    'GST / PAN holder name should contain only alphabets and spaces.': 'GST / PAN होल्डर नाम में केवल अक्षर और स्पेस होने चाहिए।',
    'Permission needed': 'अनुमति चाहिए',
    'Allow camera access to update your profile photo.': 'प्रोफाइल फोटो अपडेट करने के लिए कैमरा अनुमति दें।',
    'Allow gallery access to update your profile photo.': 'प्रोफाइल फोटो अपडेट करने के लिए गैलरी अनुमति दें।',
    'Unable to update photo': 'फोटो अपडेट नहीं हो सकी',
    'Please try again.': 'कृपया फिर से प्रयास करें।',
    'SRV Dealer Wallet': 'SRV डीलर वॉलेट',
    'SRV Premium Wallet': 'SRV प्रीमियम वॉलेट',
    'Dealer wallet for schemes, bank payouts, and dealer bonus tracking.': 'डीलर वॉलेट स्कीम्स, बैंक पेआउट और डीलर बोनस ट्रैकिंग के लिए।',
    'Luxury rewards dashboard for redemptions, transfers, and loyalty growth.': 'रिडेम्प्शन, ट्रांसफर और लॉयल्टी ग्रोथ के लिए प्रीमियम रिवॉर्ड डैशबोर्ड।',
    'Active Electricians': 'सक्रिय इलेक्ट्रीशियन',
    'Redeem Product': 'रिडीम प्रोडक्ट',
    'Bonus Withdrawals': 'बोनस निकासी',
    'Lifetime Redeem': 'लाइफटाइम रिडीम',
    'Manage dealer payouts': 'डीलर पेआउट मैनेज करें',
    'Move your wallet faster': 'अपने वॉलेट को तेजी से चलाएं',
    'Bank Transfer': 'बैंक ट्रांसफर',
    'Fast withdrawal': 'तेज निकासी',
    'Dealer Bonus': 'डीलर बोनस',
    '5% electrician bonus': '5% इलेक्ट्रीशियन बोनस',
    'Buy Schemes': 'स्कीम्स खरीदें',
    'Premium offers': 'प्रीमियम ऑफर्स',
    'Send to dealer': 'डीलर को भेजें',
    'Redeem Point History': 'रिडीम पॉइंट हिस्ट्री',
    'Elegant activity timeline': 'सुंदर एक्टिविटी टाइमलाइन',
    'Referral reward credited': 'रेफरल रिवॉर्ड जमा हुआ',
    'Today, 10:42 AM': 'आज, 10:42 AM',
    'Bank transfer processed': 'बैंक ट्रांसफर प्रोसेस हुआ',
    'Yesterday, 06:20 PM': 'कल, 06:20 PM',
    'Scheme bonus unlocked': 'स्कीम बोनस अनलॉक हुआ',
    'No detailed records yet': 'अभी कोई विस्तृत रिकॉर्ड नहीं है',
    'Activity Timeline': 'गतिविधि टाइमलाइन',
    'Your complete wallet history will appear here once bank payouts or dealer bonus activity starts.': 'जैसे ही बैंक पेआउट या डीलर बोनस गतिविधि शुरू होगी, यहां आपकी पूरी वॉलेट हिस्ट्री दिखेगी।',
    'Your complete wallet history will appear here once redemption or transfer activity starts.': 'जैसे ही रिडेम्प्शन या ट्रांसफर गतिविधि शुरू होगी, यहां आपकी पूरी वॉलेट हिस्ट्री दिखेगी।',
    'Premium rewards dashboard for redemptions, transfers, and loyalty growth.': 'रिडेम्प्शन, ट्रांसफर और लॉयल्टी ग्रोथ के लिए प्रीमियम रिवॉर्ड डैशबोर्ड।',
    'All Products': 'सभी प्रोडक्ट्स',
    'Fan Box': 'फैन बॉक्स',
    'Concealed Box': 'कन्सील्ड बॉक्स',
    'Modular Box': 'मॉड्यूलर बॉक्स',
    'MCB DB': 'एमसीबी डीबी',
    'Bus Bar': 'बस बार',
    'Exhaust Fan': 'एग्जॉस्ट फैन',
    'LED Lights': 'एलईडी लाइट्स',
    Changeover: 'चेंजओवर',
    'Main Switch': 'मेन स्विच',
    Louvers: 'लूवर्स',
    Punjab: 'पंजाब',
    Mansa: 'मानसा',
    Chauke: 'चौके',
    'FAN BOX 3"': 'फैन बॉक्स 3"',
    'FAN BOX 4"': 'फैन बॉक्स 4"',
    'FAN BOX 2.5"': 'फैन बॉक्स 2.5"',
    'FAN BOX HEAVY': 'फैन बॉक्स हेवी',
    'FAN BOX DELUXE': 'फैन बॉक्स डीलक्स',
    'FAN REGULATOR': 'फैन रेगुलेटर',
    'Search all products...': 'सभी प्रोडक्ट्स खोजें...',
    'Filter products': 'प्रोडक्ट्स फिल्टर करें',
    'Choose a category to see matching product names and items.': 'मिलते-जुलते प्रोडक्ट नाम और आइटम देखने के लिए कोई कैटेगरी चुनें।',
    Close: 'बंद करें',
    products: 'प्रोडक्ट्स',
    available: 'उपलब्ध',
    result: 'रिजल्ट',
    results: 'रिजल्ट्स',
    'No results for': 'के लिए कोई रिजल्ट नहीं',
    'Try searching by product name or size': 'प्रोडक्ट नाम या साइज से खोजने की कोशिश करें',
    "North India's Largest Manufacturer": 'नॉर्थ इंडिया का सबसे बड़ा निर्माता',
    'SRV Electricals â€” since 2000. Scan any QR to earn points!': 'SRV Electricals — 2000 से। पॉइंट्स कमाने के लिए कोई भी QR स्कैन करें!',
    'Tap card to view QR & details': 'QR और डिटेल्स देखने के लिए कार्ड टैप करें',
    Name: 'नाम',
    Code: 'कोड',
    India: 'भारत',
    Location: 'लोकेशन',
    'Business Details': 'बिजनेस डिटेल्स',
    'Connected Dealer': 'कनेक्टेड डीलर',
    'SRV Profile Card': 'एसआरवी प्रोफाइल कार्ड',
    'Save cancelled': 'सेव रद्द हुआ',
    'Folder not selected.': 'फोल्डर नहीं चुना गया।',
    'PDF saved': 'PDF सेव हो गई',
    'Profile card PDF saved to your selected device folder.': 'प्रोफाइल कार्ड PDF आपके चुने हुए डिवाइस फोल्डर में सेव हो गई।',
    'Saved in local files:': 'लोकल फाइल्स में सेव किया गया:',
    'Download failed': 'डाउनलोड फेल हुआ',
    'Unable to create the profile card PDF right now.': 'अभी प्रोफाइल कार्ड PDF नहीं बनाई जा सकी।',
    'Scan QR Code': 'QR कोड स्कैन करें',
    'Point camera at the QR sticker\non any SRV product box': 'किसी भी SRV प्रोडक्ट बॉक्स पर लगे QR स्टिकर पर कैमरा रखें',
    'Camera access allow karo taaki aap QR scan kar sako.': 'QR स्कैन करने के लिए कैमरा एक्सेस दें।',
    'Gallery access allow karo taaki aap QR image select kar sako.': 'QR इमेज चुनने के लिए गैलरी एक्सेस दें।',
    'Align QR code within the frame': 'QR कोड को फ्रेम के अंदर रखें',
    'QR Code detected': 'QR कोड मिल गया',
    'SRV MCB 32A detected': 'SRV MCB 32A मिल गया',
    'You earned +80 reward points.': 'आपने +80 रिवॉर्ड पॉइंट्स कमाए।',
    'Claim Points & Continue': 'पॉइंट्स क्लेम करें और आगे बढ़ें',
    'Scanning...': 'स्कैन हो रहा है...',
    'Start Scanning': 'स्कैन शुरू करें',
    Flashlight: 'फ्लैशलाइट',
    'Flashlight On': 'फ्लैशलाइट चालू',
    Gallery: 'गैलरी',
    'How to Scan': 'कैसे स्कैन करें',
    'Look for the QR code sticker on your SRV product box.': 'अपने SRV प्रोडक्ट बॉक्स पर QR कोड स्टिकर खोजें।',
    'Place the code inside the frame and keep the phone steady.': 'कोड को फ्रेम के अंदर रखें और फोन स्थिर रखें।',
    'Claim the points and continue to your dashboard.': 'पॉइंट्स क्लेम करें और अपने डैशबोर्ड पर जाएं।',
    'Invalid number': 'अमान्य नंबर',
    'Please enter a valid 10-digit mobile number.': 'कृपया सही 10 अंकों का मोबाइल नंबर दर्ज करें।',
    'User Found': 'यूजर मिला',
    'Enter Mobile Number': 'मोबाइल नंबर दर्ज करें',
    'Scan QR': 'QR स्कैन करें',
    'Open the main scan page to scan the QR code from the middle bottom navigation.': 'बीच वाले नीचे नेविगेशन से QR कोड स्कैन करने के लिए मुख्य स्कैन पेज खोलें।',
    'Open Scan Page': 'स्कैन पेज खोलें',
    'Go to the center QR scanner page': 'बीच वाले QR स्कैनर पेज पर जाएं',
    'Rewards Store': 'रिवॉर्ड्स स्टोर',
    Cashback: 'कैशबैक',
    Gifts: 'गिफ्ट्स',
    More: 'और',
    Redeem: 'रिडीम',
    'to unlock': 'अनलॉक होने तक',
    'Mega Rewards Event!': 'मेगा रिवॉर्ड्स इवेंट!',
    'Earn 2x points on all scans this week. Limited time offer!': 'इस हफ्ते सभी स्कैन पर 2x पॉइंट्स कमाएं। सीमित समय का ऑफर!',
    'Learn More': 'और जानें',
    'Notification Center': 'नोटिफिकेशन सेंटर',
    'Stay updated with SRV': 'SRV के साथ अपडेट रहें',
    'Important price updates, reward alerts, and account notices in one place.': 'महत्वपूर्ण प्राइस अपडेट, रिवॉर्ड अलर्ट और अकाउंट नोटिस एक ही जगह।',
    'Back Home': 'होम वापस',
    'Latest updates': 'ताज़ा अपडेट',
    new: 'नए',
    'Price Update': 'प्राइस अपडेट',
    'The price of 4 way DD has been updated to Rs.306.': '4 way DD की कीमत अब Rs.306 कर दी गई है।',
    '2 hr ago': '2 घंटे पहले',
    'Price Alert': 'प्राइस अलर्ट',
    'The price of 6 Way DD has been updated to Rs.363.': '6 Way DD की कीमत अब Rs.363 कर दी गई है।',
    '3 hr ago': '3 घंटे पहले',
    'Scheme Notice': 'स्कीम नोटिस',
    'Selected SRV reward schemes have updated slabs for this week.': 'इस हफ्ते के लिए चुनी गई SRV रिवॉर्ड स्कीम्स के स्लैब अपडेट हुए हैं।',
    Rewards: 'रिवॉर्ड्स',
    'Important SRV announcement': 'महत्वपूर्ण SRV घोषणा',
    'Keep your profile and bank details updated for smooth redemptions and withdrawals.': 'स्मूद रिडेम्प्शन और निकासी के लिए अपनी प्रोफाइल और बैंक डिटेल्स अपडेट रखें।',
    Alerts: 'अलर्ट्स',
    Today: 'आज',
    Filter: 'फिल्टर',
    'Transfer Point': 'पॉइंट ट्रांसफर',
    'This Month': 'इस महीने',
    'Last 30 Days': 'पिछले 30 दिन',
    Processed: 'प्रोसेस्ड',
    Completed: 'पूरा हुआ',
    Success: 'सफल',
    Credited: 'जमा हुआ',
    'Premium Fan Box Scheme': 'प्रीमियम फैन बॉक्स स्कीम',
    'Bank Transfer Request': 'बैंक ट्रांसफर रिक्वेस्ट',
    'Points Sent to Dealer': 'डीलर को भेजे गए पॉइंट्स',
    '5% bonus from electrician redemptions': 'इलेक्ट्रीशियन रिडेम्प्शन से 5% बोनस',
    'Festival Reward Scheme': 'फेस्टिवल रिवॉर्ड स्कीम',
    Hot: 'हॉट',
    New: 'नया',
    Live: 'लाइव',
    'Festive Bonus': 'फेस्टिव बोनस',
    'Dealer Growth Offer': 'डीलर ग्रोथ ऑफर',
    'Scan & Win': 'स्कैन और जीतें',
    'Get 500 extra points on selected premium range purchases.': 'चुनी हुई प्रीमियम रेंज खरीद पर 500 अतिरिक्त पॉइंट्स पाएं।',
    'Complete your monthly target and unlock a surprise gift slab.': 'अपना मासिक टारगेट पूरा करें और सरप्राइज गिफ्ट स्लैब अनलॉक करें।',
    'Scan 25 products this month to get accelerated reward points.': 'इस महीने 25 प्रोडक्ट स्कैन करके तेज रिवॉर्ड पॉइंट्स पाएं।',
    'Enter amount': 'राशि दर्ज करें',
    'Please enter a valid withdrawal amount.': 'कृपया सही निकासी राशि दर्ज करें।',
    'Insufficient balance': 'पर्याप्त बैलेंस नहीं',
    'Withdrawal amount cannot be more than your available dealer bonus.': 'निकासी राशि उपलब्ध डीलर बोनस से अधिक नहीं हो सकती।',
    'Request submitted': 'अनुरोध भेज दिया गया',
    'Rs. 250 will be transferred to your bank account after approval.': 'स्वीकृति के बाद Rs. 250 आपके बैंक खाते में भेजे जाएंगे।',
    'Rs. 500 will be transferred to your bank account after approval.': 'स्वीकृति के बाद Rs. 500 आपके बैंक खाते में भेजे जाएंगे।',
    'Rs. 1000 will be transferred to your bank account after approval.': 'स्वीकृति के बाद Rs. 1000 आपके बैंक खाते में भेजे जाएंगे।',
    '5% Auto Bonus': '5% ऑटो बोनस',
    'GET YOUR BONUS': 'अपना बोनस पाएं',
    '5% of the points redeemed by any electrician will be credited to your dealer wallet. 1 point = 1 INR, and you can withdraw it directly to your bank account.': 'किसी भी इलेक्ट्रीशियन द्वारा रिडीम किए गए पॉइंट्स का 5% आपके डीलर वॉलेट में जमा होगा। 1 पॉइंट = 1 INR, और आप इसे सीधे अपने बैंक खाते में निकाल सकते हैं।',
    'Available to withdraw': 'निकासी के लिए उपलब्ध',
    '1 Point = 1 INR': '1 पॉइंट = 1 INR',
    'Active electricians': 'सक्रिय इलेक्ट्रीशियन',
    'Monthly redeemed pts': 'मासिक रिडीम्ड पॉइंट्स',
    'This month bonus': 'इस महीने का बोनस',
    'How it works': 'यह कैसे काम करता है',
    'Electrician points redeem hote hi 5% dealer bonus auto-credit ho jata hai.': 'इलेक्ट्रीशियन पॉइंट्स रिडीम होते ही 5% डीलर बोनस अपने आप जमा हो जाता है।',
    'Bonus balance update hota rahega and 1 point ki value 1 INR rahegi.': 'बोनस बैलेंस अपडेट होता रहेगा और 1 पॉइंट की वैल्यू 1 INR रहेगी।',
    'Aap bank transfer request karke amount withdraw kar sakte hain.': 'आप बैंक ट्रांसफर रिक्वेस्ट करके राशि निकाल सकते हैं।',
    'Withdraw to bank': 'बैंक में निकासी',
    'Transfer to ICICI Bank ending 2048': 'ICICI Bank ending 2048 में ट्रांसफर',
    'Enter amount in rupees': 'रुपयों में राशि दर्ज करें',
    'Request bank transfer': 'बैंक ट्रांसफर रिक्वेस्ट करें',
    'Recent bonus activity': 'हाल की बोनस गतिविधि',
    Redeemed: 'रिडीम किया',
    'Active Orders': 'सक्रिय ऑर्डर',
    'Last Delivery': 'आखिरी डिलीवरी',
    'Scan & Transfer': 'स्कैन और ट्रांसफर',
    'Scan any SRV product QR to transfer points to dealers instantly.': 'SRV प्रोडक्ट QR स्कैन करके तुरंत डीलर को पॉइंट्स ट्रांसफर करें।',
    'Open Scanner': 'स्कैनर खोलें',
    pts: 'पॉइंट्स',
    'Today, 11:40 AM': 'आज, 11:40 AM',
    'Yesterday, 06:15 PM': 'कल, 06:15 PM',
    '05 Apr 2026': '05 अप्रैल 2026',
    'Dealer Calling Desk': 'डीलर कॉलिंग डेस्क',
    'Reach your electricians instantly': 'अपने इलेक्ट्रीशियन से तुरंत जुड़ें',
    'Use normal phone call or WhatsApp call actions to connect with any associated electrician.': 'किसी भी जुड़े हुए इलेक्ट्रीशियन से संपर्क करने के लिए सामान्य कॉल या व्हाट्सऐप कॉल का उपयोग करें।',
    'Choose App Language': 'ऐप भाषा चुनें',
    'Switch any time from App Settings': 'कभी भी App Settings से बदलें',
    'verification successfully done.': 'वेरिफिकेशन सफलतापूर्वक पूरा हुआ।',
    Silver: 'सिल्वर',
    Gold: 'गोल्ड',
    Platinum: 'प्लैटिनम',
    Diamond: 'डायमंड',
    Member: 'मेंबर',
    Current: 'वर्तमान',
    'Current Reward Level': 'वर्तमान रिवॉर्ड स्तर',
    'Your electrician grading is based on total reward points earned through scans and redemptions.': 'आपकी इलेक्ट्रीशियन ग्रेडिंग स्कैन और रिडेम्प्शन से कमाए गए कुल रिवॉर्ड पॉइंट्स पर आधारित है।',
    'Current points': 'वर्तमान पॉइंट्स',
    'Tier range': 'टियर रेंज',
    'Points grading system': 'पॉइंट ग्रेडिंग सिस्टम',
    '0 - 1000 points': '0 - 1000 पॉइंट्स',
    '1001 - 5000 points': '1001 - 5000 पॉइंट्स',
    '5001 - 10000 points': '5001 - 10000 पॉइंट्स',
    '10000+ points': '10000+ पॉइंट्स',
    'Starting level for electricians building up their first reward points.': 'पहले रिवॉर्ड पॉइंट्स जोड़ने वाले इलेक्ट्रीशियन के लिए शुरुआती स्तर।',
    'Strong reward status with steady scanning and reward collection.': 'नियमित स्कैनिंग और रिवॉर्ड कलेक्शन के साथ मजबूत रिवॉर्ड स्तर।',
    'Premium level for electricians with high reward point activity.': 'ज्यादा रिवॉर्ड पॉइंट एक्टिविटी वाले इलेक्ट्रीशियन के लिए प्रीमियम स्तर।',
    'Top elite reward level for electricians with the strongest point balance.': 'सबसे मजबूत पॉइंट बैलेंस वाले इलेक्ट्रीशियन के लिए सर्वोच्च एलीट रिवॉर्ड स्तर।',
    'Dealer Network': 'डीलर नेटवर्क',
    'Connected electricians': 'जुड़े हुए इलेक्ट्रीशियन',
    'Dealers can review every connected electrician here and add new electricians to their network from the same page.': 'डीलर यहां अपने सभी जुड़े हुए इलेक्ट्रीशियन देख सकते हैं और इसी पेज से नए इलेक्ट्रीशियन जोड़ सकते हैं।',
    'Add Electrician': 'इलेक्ट्रीशियन जोड़ें',
    Active: 'सक्रिय',
    Pending: 'लंबित',
    records: 'रिकॉर्ड',
    'Search by name, phone, or city': 'नाम, फोन या शहर से खोजें',
    'Electrician directory': 'इलेक्ट्रीशियन डायरेक्टरी',
    'Add electrician': 'इलेक्ट्रीशियन जोड़ें',
    'Verify the number first, then complete the remaining details.': 'पहले नंबर वेरिफाई करें, फिर बाकी जानकारी भरें।',
    'Electrician name': 'इलेक्ट्रीशियन का नाम',
    'Enter full name': 'पूरा नाम दर्ज करें',
    'Electrician number': 'इलेक्ट्रीशियन नंबर',
    '10-digit mobile number': '10 अंकों का मोबाइल नंबर',
    'OTP sent to +91': '+91 पर OTP भेजा गया',
    'Demo OTP': 'डेमो OTP',
    'Enter OTP': 'OTP दर्ज करें',
    Confirm: 'कन्फर्म',
    'Phone number verified successfully': 'फोन नंबर सफलतापूर्वक वेरिफाई हो गया',
    'City or district': 'शहर या जिला',
    'Invalid OTP': 'गलत OTP',
    'Please enter the correct 4-digit OTP to verify the phone number.': 'फोन नंबर वेरिफाई करने के लिए सही 4 अंकों का OTP दर्ज करें।',
    'Connected today': 'आज जुड़े',
    'Connected 3 days ago': '3 दिन पहले जुड़े',
    'Invite pending': 'निमंत्रण लंबित',
    'Added just now': 'अभी जोड़ा गया',
    'Capture a photo, crop it if needed, then confirm it on the next screen': 'फोटो लें, फिर अगली स्क्रीन पर कन्फर्म करें',
    'Select a photo, crop it if needed, then confirm it on the next screen': 'फोटो चुनें, फिर अगली स्क्रीन पर कन्फर्म करें',
    '+120 this week': '+120 इस सप्ताह',
    'Rs 100 Cashback': 'Rs 100 कैशबैक',
    'Direct UPI or bank transfer': 'सीधा UPI या बैंक ट्रांसफर',
    'Amazon Voucher': 'अमेज़न वाउचर',
    'Rs 200 gift card code': 'Rs 200 गिफ्ट कार्ड कोड',
    'SRV Product Bundle': 'SRV प्रोडक्ट बंडल',
    'Free kit worth Rs 500': 'Rs 500 की फ्री किट',
    'Paytm Voucher': 'Paytm वाउचर',
    'Rs 150 wallet credit': 'Rs 150 वॉलेट क्रेडिट',
    'Premium Toolkit': 'प्रीमियम टूलकिट',
    'Professional electrician kit': 'प्रोफेशनल इलेक्ट्रीशियन किट',
    'Flipkart Voucher': 'फ्लिपकार्ट वाउचर',
    'Rs 300 shopping voucher': 'Rs 300 शॉपिंग वाउचर',
  },
  Punjabi: {
    Home: 'ਹੋਮ',
    Product: 'ਪ੍ਰੋਡਕਟ',
    Wallet: 'ਵਾਲਿਟ',
    Profile: 'ਪ੍ਰੋਫਾਈਲ',
    Electricians: 'ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ',
    SCAN: 'ਸਕੈਨ',
    Continue: 'ਜਾਰੀ ਰੱਖੋ',
    Login: 'ਲੌਗਿਨ',
    Verify: 'ਵੇਰੀਫਾਈ',
    OTP: 'OTP',
    Password: 'ਪਾਸਵਰਡ',
    Notifications: 'ਨੋਟੀਫਿਕੇਸ਼ਨ',
    Enter: 'ਦਰਜ ਕਰੋ',
    'Create Account': 'ਅਕਾਊਂਟ ਬਣਾਓ',
    'Welcome to SRV': 'SRV ਵਿੱਚ ਤੁਹਾਡਾ ਸੁਆਗਤ ਹੈ',
    'Choose your language': 'ਆਪਣੀ ਭਾਸ਼ਾ ਚੁਣੋ',
    'Choose your role': 'ਆਪਣਾ ਰੋਲ ਚੁਣੋ',
    'Choose your role to start the onboarding journey.': 'ਆਨਬੋਰਡਿੰਗ ਸ਼ੁਰੂ ਕਰਨ ਲਈ ਆਪਣਾ ਰੋਲ ਚੁਣੋ।',
    'Pick your preferred language first, then continue to the onboarding screen.': 'ਪਹਿਲਾਂ ਆਪਣੀ ਮਨਪਸੰਦ ਭਾਸ਼ਾ ਚੁਣੋ, ਫਿਰ ਆਨਬੋਰਡਿੰਗ ਸਕਰੀਨ ਤੇ ਅੱਗੇ ਵਧੋ।',
    'Professional authentication flow aligned with the app design system.': 'ਐਪ ਡਿਜ਼ਾਈਨ ਸਿਸਟਮ ਨਾਲ ਮਿਲਦਾ ਪ੍ਰੋਫੈਸ਼ਨਲ ਔਥੈਂਟੀਕੇਸ਼ਨ ਫਲੋ।',
    'Language Setup': 'ਭਾਸ਼ਾ ਸੈਟਅਪ',
    'Account Setup': 'ਅਕਾਊਂਟ ਸੈਟਅਪ',
    'App Preferences': 'ਐਪ ਪਸੰਦਾਂ',
    'CHOOSE YOUR LANGUAGE': 'ਆਪਣੀ ਭਾਸ਼ਾ ਚੁਣੋ',
    'Use the same language across the complete SRV app experience.': 'ਪੂਰੇ SRV ਐਪ ਅਨੁਭਵ ਵਿੱਚ ਇੱਕੋ ਭਾਸ਼ਾ ਵਰਤੋ।',
    'CHOOSE YOUR ROLE': 'ਆਪਣਾ ਰੋਲ ਚੁਣੋ',
    'This keeps rewards, verification and account setup perfectly aligned.': 'ਇਸ ਨਾਲ ਰਿਵਾਰਡ, ਵੇਰੀਫਿਕੇਸ਼ਨ ਅਤੇ ਅਕਾਊਂਟ ਸੈਟਅਪ ਠੀਕ ਤਰ੍ਹਾਂ ਮਿਲੇ ਰਹਿੰਦੇ ਹਨ।',
    Authentication: 'ਔਥੈਂਟੀਕੇਸ਼ਨ',
    'Welcome back': 'ਵਾਪਸੀ ਤੇ ਸੁਆਗਤ ਹੈ',
    'Create your account': 'ਆਪਣਾ ਅਕਾਊਂਟ ਬਣਾਓ',
    'Smooth inputs, full-screen layout, and no keyboard overlap while typing.': 'ਸਮੂਥ ਇਨਪੁੱਟ, ਫੁੱਲ-ਸਕਰੀਨ ਲੇਆਉਟ ਅਤੇ ਟਾਈਪ ਕਰਦੇ ਸਮੇਂ ਕੋਈ ਕੀਬੋਰਡ ਓਵਰਲੈਪ ਨਹੀਂ।',
    Electrician: 'ਇਲੈਕਟ੍ਰੀਸ਼ਨ',
    Dealer: 'ਡੀਲਰ',
    'Field rewards and quick verification': 'ਫੀਲਡ ਰਿਵਾਰਡ ਅਤੇ ਤੇਜ਼ ਵੇਰੀਫਿਕੇਸ਼ਨ',
    'Business onboarding and account access': 'ਬਿਜ਼ਨਸ ਆਨਬੋਰਡਿੰਗ ਅਤੇ ਅਕਾਊਂਟ ਐਕਸੈੱਸ',
    'Select Login Method': 'ਲੌਗਿਨ ਤਰੀਕਾ ਚੁਣੋ',
    'Login with OTP': 'OTP ਨਾਲ ਲੌਗਿਨ',
    'Login with Password': 'ਪਾਸਵਰਡ ਨਾਲ ਲੌਗਿਨ',
    'Mobile Number': 'ਮੋਬਾਈਲ ਨੰਬਰ',
    'Email Address': 'ਈਮੇਲ ਪਤਾ',
    'Enter mobile number': 'ਮੋਬਾਈਲ ਨੰਬਰ ਦਰਜ ਕਰੋ',
    'Enter owner or business name': 'ਮਾਲਕ ਜਾਂ ਬਿਜ਼ਨਸ ਦਾ ਨਾਮ ਦਰਜ ਕਰੋ',
    'Enter GST or PAN number': 'GST ਜਾਂ PAN ਨੰਬਰ ਦਰਜ ਕਰੋ',
    'Enter holder name': 'ਹੋਲਡਰ ਦਾ ਨਾਮ ਦਰਜ ਕਰੋ',
    'Enter 4 digit OTP': '4 ਅੰਕਾਂ ਦਾ OTP ਦਰਜ ਕਰੋ',
    'Verify OTP': 'OTP ਵੇਰੀਫਾਈ ਕਰੋ',
    'OTP sent to': 'OTP ਭੇਜਿਆ ਗਿਆ',
    'OTP verification successful.': 'OTP ਵੇਰੀਫਿਕੇਸ਼ਨ ਸਫਲ ਹੋਇਆ।',
    'OTP verified successfully.': 'OTP ਸਫਲਤਾਪੂਰਵਕ ਵੇਰੀਫਾਈ ਹੋਇਆ।',
    'Logging In...': 'ਲੌਗਿਨ ਹੋ ਰਿਹਾ ਹੈ...',
    'Enter password': 'ਪਾਸਵਰਡ ਦਰਜ ਕਰੋ',
    'Step 1 of 5': 'ਸਟੈਪ 1 ਆਫ 5',
    'Step 2 of 5': 'ਸਟੈਪ 2 ਆਫ 5',
    'Step 3 of 5': 'ਸਟੈਪ 3 ਆਫ 5',
    'Step 4 of 5': 'ਸਟੈਪ 4 ਆਫ 5',
    'Step 5 of 5': 'ਸਟੈਪ 5 ਆਫ 5',
    'Business Profile': 'ਬਿਜ਼ਨਸ ਪ੍ਰੋਫਾਈਲ',
    'Business Address': 'ਬਿਜ਼ਨਸ ਪਤਾ',
    'Location Details': 'ਲੋਕੇਸ਼ਨ ਵੇਰਵਾ',
    'Business Identity': 'ਬਿਜ਼ਨਸ ਪਹਿਚਾਣ',
    'Mobile Verification': 'ਮੋਬਾਈਲ ਵੇਰੀਫਿਕੇਸ਼ਨ',
    'Password & Consent': 'ਪਾਸਵਰਡ ਅਤੇ ਸਹਿਮਤੀ',
    'Continue to Location': 'ਲੋਕੇਸ਼ਨ ਵੱਲ ਜਾਰੀ ਰੱਖੋ',
    'Continue to Identity': 'ਪਹਿਚਾਣ ਵੱਲ ਜਾਰੀ ਰੱਖੋ',
    'Continue to Mobile Verification': 'ਮੋਬਾਈਲ ਵੇਰੀਫਿਕੇਸ਼ਨ ਵੱਲ ਜਾਰੀ ਰੱਖੋ',
    'Continue to Security': 'ਸਿਕਿਊਰਟੀ ਵੱਲ ਜਾਰੀ ਰੱਖੋ',
    'Enter complete business address': 'ਪੂਰਾ ਬਿਜ਼ਨਸ ਪਤਾ ਦਰਜ ਕਰੋ',
    'Creating Account...': 'ਅਕਾਊਂਟ ਬਣਾਇਆ ਜਾ ਰਿਹਾ ਹੈ...',
    'Skip for Now': 'ਹਾਲੇ ਛੱਡੋ',
    'Enter the owner or business name, email address, and business address in a clean business format.': 'ਮਾਲਕ ਜਾਂ ਬਿਜ਼ਨਸ ਦਾ ਨਾਮ, ਈਮੇਲ ਅਤੇ ਬਿਜ਼ਨਸ ਪਤਾ ਠੀਕ ਤਰੀਕੇ ਨਾਲ ਦਰਜ ਕਰੋ।',
    'Review the state, city, and pincode. Auto-filled details can still be edited if needed.': 'ਰਾਜ, ਸ਼ਹਿਰ ਅਤੇ ਪਿੰਨਕੋਡ ਵੇਖੋ। ਲੋੜ ਹੋਣ ਤੇ ਆਟੋ-ਫਿਲ ਕੀਤੀ ਜਾਣਕਾਰੀ ਬਦਲੀ ਜਾ ਸਕਦੀ ਹੈ।',
    'Add GST or PAN details now, or skip this step and update them later from Edit Profile.': 'ਹੁਣ GST ਜਾਂ PAN ਵੇਰਵਾ ਜੋੜੋ ਜਾਂ ਇਹ ਕਦਮ ਛੱਡ ਕੇ ਬਾਅਦ ਵਿੱਚ Edit Profile ਤੋਂ ਅਪਡੇਟ ਕਰੋ।',
    'Verify the dealer mobile number before moving to the final security step.': 'ਆਖਰੀ ਸਿਕਿਊਰਟੀ ਕਦਮ ਤੋਂ ਪਹਿਲਾਂ ਡੀਲਰ ਮੋਬਾਈਲ ਨੰਬਰ ਵੇਰੀਫਾਈ ਕਰੋ।',
    'Create a password if you want and finish the account setup securely.': 'ਚਾਹੋ ਤਾਂ ਪਾਸਵਰਡ ਬਣਾਓ ਅਤੇ ਅਕਾਊਂਟ ਸੈਟਅਪ ਸੁਰੱਖਿਅਤ ਤਰੀਕੇ ਨਾਲ ਪੂਰਾ ਕਰੋ।',
    'Current Address': 'ਮੌਜੂਦਾ ਪਤਾ',
    'Fetching current address...': 'ਮੌਜੂਦਾ ਪਤਾ ਲਿਆ ਜਾ ਰਿਹਾ ਹੈ...',
    Locating: 'ਲੋਕੇਟ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ',
    Resend: 'ਮੁੜ ਭੇਜੋ',
    'Phone verification successful.': 'ਫੋਨ ਵੇਰੀਫਿਕੇਸ਼ਨ ਸਫਲ ਰਿਹਾ।',
    'Password is optional. Leave both fields blank if you want to skip it.': 'ਪਾਸਵਰਡ ਵਿਕਲਪਿਕ ਹੈ। ਜੇ ਛੱਡਣਾ ਚਾਹੁੰਦੇ ਹੋ ਤਾਂ ਦੋਵੇਂ ਫੀਲਡ ਖਾਲੀ ਛੱਡੋ।',
    'Password (Optional)': 'ਪਾਸਵਰਡ (ਵਿਕਲਪਿਕ)',
    'Confirm Password (Optional)': 'ਪਾਸਵਰਡ ਪੁਸ਼ਟੀ (ਵਿਕਲਪਿਕ)',
    'Create password if you want': 'ਚਾਹੋ ਤਾਂ ਪਾਸਵਰਡ ਬਣਾਓ',
    'Re-enter password': 'ਪਾਸਵਰਡ ਮੁੜ ਦਰਜ ਕਰੋ',
    'By creating an account, you agree to the Terms & Conditions and Privacy Policy.': 'ਅਕਾਊਂਟ ਬਣਾਕੇ ਤੁਸੀਂ ਨਿਯਮ ਅਤੇ ਸ਼ਰਤਾਂ ਅਤੇ ਪ੍ਰਾਈਵੇਸੀ ਪਾਲਿਸੀ ਨਾਲ ਸਹਿਮਤ ਹੁੰਦੇ ਹੋ।',
    'Full Name': 'ਪੂਰਾ ਨਾਮ',
    'Enter your full name': 'ਆਪਣਾ ਪੂਰਾ ਨਾਮ ਦਰਜ ਕਰੋ',
    'Dealer Verification Number': 'ਡੀਲਰ ਵੇਰੀਫਿਕੇਸ਼ਨ ਨੰਬਰ',
    'Enter dealer mobile number': 'ਡੀਲਰ ਮੋਬਾਈਲ ਨੰਬਰ ਦਰਜ ਕਰੋ',
    Address: 'ਪਤਾ',
    'Enter your complete address': 'ਆਪਣਾ ਪੂਰਾ ਪਤਾ ਦਰਜ ਕਰੋ',
    'Detected Location Details': 'ਪਤਾ ਲੱਗੀ ਲੋਕੇਸ਼ਨ ਜਾਣਕਾਰੀ',
    State: 'ਰਾਜ',
    City: 'ਸ਼ਹਿਰ',
    Pincode: 'ਪਿੰਨਕੋਡ',
    'Your Phone Number': 'ਤੁਹਾਡਾ ਫੋਨ ਨੰਬਰ',
    'Enter your phone number': 'ਆਪਣਾ ਫੋਨ ਨੰਬਰ ਦਰਜ ਕਰੋ',
    Opening: 'ਖੋਲ੍ਹਿਆ ਜਾ ਰਿਹਾ ਹੈ',
    'Scan & Earn': 'ਸਕੈਨ ਕਰੋ ਅਤੇ ਕਮਾਓ',
    'Instant points': 'ਤੁਰੰਤ ਪੌਇੰਟ',
    'Balance & history': 'ਬੈਲੈਂਸ ਅਤੇ ਹਿਸਟਰੀ',
    WhatsApp: 'ਵਟਸਐਪ',
    'Premium support': 'ਪ੍ਰੀਮੀਅਮ ਸਹਾਇਤਾ',
    'Top Picks': 'ਟਾਪ ਪਿਕਸ',
    'Featured products': 'ਫੀਚਰਡ ਪ੍ਰੋਡਕਟ',
    All: 'ਸਾਰੇ',
    Boxes: 'ਬਾਕਸ',
    Fans: 'ਫੈਨ',
    'View all': 'ਸਾਰੇ ਵੇਖੋ',
    'Recent Activity': 'ਹਾਲੀਆ ਗਤੀਵਿਧੀ',
    'Latest actions': 'ਤਾਜ਼ਾ ਕਾਰਵਾਈਆਂ',
    'QR scanned successfully': 'QR ਸਫਲਤਾਪੂਰਵਕ ਸਕੈਨ ਹੋਇਆ',
    'Today, 10:23 AM': 'ਅੱਜ, 10:23 AM',
    Yesterday: 'ਕੱਲ੍ਹ',
    '2 days ago': '2 ਦਿਨ ਪਹਿਲਾਂ',
    'Reward redeemed': 'ਰਿਵਾਰਡ ਰੀਡੀਮ ਹੋਇਆ',
    'Referral bonus added': 'ਰੈਫਰਲ ਬੋਨਸ ਜੋੜਿਆ ਗਿਆ',
    'Total Points': 'ਕੁੱਲ ਪੌਇੰਟ',
    'Member Tier': 'ਮੈਂਬਰ ਟੀਅਰ',
    'Top reward level unlocked': 'ਟਾਪ ਰਿਵਾਰਡ ਲੈਵਲ ਅਨਲੌਕ ਹੋ ਗਿਆ',
    'Scan to Earn': 'ਸਕੈਨ ਕਰਕੇ ਕਮਾਓ',
    Popular: 'ਲੋਕਪ੍ਰਿਯ',
    'Top Pick': 'ਟਾਪ ਪਿਕ',
    'Associate Electrician': 'ਇਲੈਕਟ੍ਰੀਸ਼ਨ ਜੋੜੋ',
    'My Redemption': 'ਮੇਰਾ ਰਿਡੈਂਪਸ਼ਨ',
    'Gift Store': 'ਗਿਫਟ ਸਟੋਰ',
    'Transfer Points': 'ਪੁਆਇੰਟ ਟ੍ਰਾਂਸਫਰ',
    'My Orders': 'ਮੇਰੇ ਆਰਡਰ',
    'Bank Details': 'ਬੈਂਕ ਵੇਰਵਾ',
    'Secure payouts to your bank': 'ਆਪਣੇ ਬੈਂਕ ਨੂੰ ਸੁਰੱਖਿਅਤ ਪੇਆਊਟ',
    'BANK TRANSFER': 'ਬੈਂਕ ਟ੍ਰਾਂਸਫਰ',
    'Account Holder Name': 'ਖਾਤਾਧਾਰਕ ਦਾ ਨਾਂ',
    'Enter Account Holder Name': 'ਖਾਤਾਧਾਰਕ ਦਾ ਨਾਂ ਦਰਜ ਕਰੋ',
    'Account Number': 'ਖਾਤਾ ਨੰਬਰ',
    'Enter Account Number': 'ਖਾਤਾ ਨੰਬਰ ਦਰਜ ਕਰੋ',
    'IFSC Code': 'IFSC ਕੋਡ',
    'Enter IFSC Code': 'IFSC ਕੋਡ ਦਰਜ ਕਰੋ',
    'Select Bank': 'ਬੈਂਕ ਚੁਣੋ',
    'UPI ID': 'UPI ID',
    'Enter UPI ID': 'UPI ID ਦਰਜ ਕਰੋ',
    'Please enter a valid UPI ID in the format name@bank.': 'ਕਿਰਪਾ ਕਰਕੇ name@bank ਫਾਰਮੈਟ ਵਿੱਚ ਸਹੀ UPI ID ਦਰਜ ਕਰੋ।',
    'Add your bank account and UPI ID for smooth payouts': 'ਆਸਾਨ ਪੇਆਊਟ ਲਈ ਆਪਣਾ ਬੈਂਕ ਖਾਤਾ ਅਤੇ UPI ID ਜੋੜੋ',
    'Saved': 'ਸੇਵ ਕੀਤਾ',
    'Bank details saved successfully!': 'ਬੈਂਕ ਵੇਰਵਾ ਸਫਲਤਾਪੂਰਵਕ ਸੇਵ ਹੋ ਗਿਆ!',
    'Required fields': 'ਲੋੜੀਂਦੇ ਖੇਤਰ',
    'Please fill all required fields.': 'ਕਿਰਪਾ ਕਰਕੇ ਸਾਰੇ ਲੋੜੀਂਦੇ ਖੇਤਰ ਭਰੋ।',
    'Invalid account holder name': 'ਗਲਤ ਖਾਤਾਧਾਰਕ ਨਾਂ',
    'Account holder name should contain only letters and spaces.': 'ਖਾਤਾਧਾਰਕ ਨਾਂ ਵਿੱਚ ਸਿਰਫ ਅੱਖਰ ਅਤੇ ਖਾਲੀ ਥਾਂ ਹੋਣੀਆਂ ਚਾਹੀਦੀਆਂ ਹਨ।',
    'Invalid account number': 'ਗਲਤ ਖਾਤਾ ਨੰਬਰ',
    'Account number should contain only numbers.': 'ਖਾਤਾ ਨੰਬਰ ਵਿੱਚ ਸਿਰਫ ਅੰਕ ਹੋਣੇ ਚਾਹੀਦੇ ਹਨ।',
    'Invalid UPI ID': 'ਗਲਤ UPI ID',
    'Refer To A Friend': 'ਦੋਸਤ ਨੂੰ ਰੈਫਰ ਕਰੋ',
    'Need Help': 'ਮਦਦ ਚਾਹੀਦੀ ਹੈ',
    'Offers & Promotions': 'ਆਫਰ ਅਤੇ ਪ੍ਰਮੋਸ਼ਨ',
    'App Settings': 'ਐਪ ਸੈਟਿੰਗਜ਼',
    'Scan History': 'ਸਕੈਨ ਹਿਸਟਰੀ',
    'Contact Support': 'ਸੰਪਰਕ ਸਹਾਇਤਾ',
    connected: 'ਜੁੜੇ ਹੋਏ',
    contacts: 'ਸੰਪਰਕ',
    'Open phone and WhatsApp actions': 'ਫੋਨ ਅਤੇ ਵਟਸਐਪ ਐਕਸ਼ਨ ਖੋਲ੍ਹੋ',
    'Top dealer grade unlocked': 'ਟਾਪ ਡੀਲਰ ਗ੍ਰੇਡ ਅਨਲੌਕ ਹੋ ਗਿਆ',
    'Payout and history': 'ਪੇਆਉਟ ਅਤੇ ਹਿਸਟਰੀ',
    'Call Electrician': 'ਇਲੈਕਟ੍ਰੀਸ਼ਨ ਨੂੰ ਕਾਲ ਕਰੋ',
    'Reach your network': 'ਆਪਣੇ ਨੈੱਟਵਰਕ ਤੱਕ ਪਹੁੰਚੋ',
    'Business support': 'ਬਿਜ਼ਨਸ ਸਹਾਇਤਾ',
    Catalog: 'ਕੈਟਾਲਾਗ',
    'Hot Deal': 'ਹਾਟ ਡੀਲ',
    'Dealer Growth': 'ਡੀਲਰ ਗ੍ਰੋਥ',
    'My Profile': 'ਮੇਰੀ ਪ੍ਰੋਫਾਈਲ',
    'Review photo': 'ਫੋਟੋ ਵੇਖੋ',
    Done: 'ਮੁਕੰਮਲ',
    'Edit Profile': 'ਪ੍ਰੋਫਾਈਲ ਐਡਿਟ ਕਰੋ',
    'Profile Photo': 'ਪ੍ਰੋਫਾਈਲ ਫੋਟੋ',
    'Phone Number': 'ਫੋਨ ਨੰਬਰ',
    Email: 'ਈਮੇਲ',
    'Not provided': 'ਦਿੱਤਾ ਨਹੀਂ ਗਿਆ',
    'Dealer Partner': 'ਡੀਲਰ ਪਾਰਟਨਰ',
    'Electrician Partner': 'ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ ਪਾਰਟਨਰ',
    'GST Holder Name': 'GST ਹੋਲਡਰ ਨਾਮ',
    'GST Number': 'GST ਨੰਬਰ',
    'PAN Holder Name': 'PAN ਹੋਲਡਰ ਨਾਮ',
    'PAN Number': 'PAN ਨੰਬਰ',
    'Dealer Code': 'ਡੀਲਰ ਕੋਡ',
    'Electrician Code': 'ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ ਕੋਡ',
    'All Products': 'ਸਾਰੇ ਪ੍ਰੋਡਕਟ',
    'Fan Box': 'ਫੈਨ ਬਾਕਸ',
    'Concealed Box': 'ਕੰਸੀਲਡ ਬਾਕਸ',
    'Modular Box': 'ਮੋਡੀਊਲਰ ਬਾਕਸ',
    'MCB DB': 'ਐਮਸੀਬੀ ਡੀਬੀ',
    'Bus Bar': 'ਬਸ ਬਾਰ',
    'Exhaust Fan': 'ਐਗਜ਼ੌਸਟ ਫੈਨ',
    'LED Lights': 'ਐਲਈਡੀ ਲਾਈਟਾਂ',
    Changeover: 'ਚੇਂਜਓਵਰ',
    'Main Switch': 'ਮੇਨ ਸਵਿੱਚ',
    Louvers: 'ਲੂਵਰਜ਼',
    Punjab: 'ਪੰਜਾਬ',
    Mansa: 'ਮਾਨਸਾ',
    Chauke: 'ਚੌਕੇ',
    'FAN BOX 3"': 'ਫੈਨ ਬਾਕਸ 3"',
    'FAN BOX 4"': 'ਫੈਨ ਬਾਕਸ 4"',
    'FAN BOX 2.5"': 'ਫੈਨ ਬਾਕਸ 2.5"',
    'FAN BOX HEAVY': 'ਫੈਨ ਬਾਕਸ ਹੈਵੀ',
    'FAN BOX DELUXE': 'ਫੈਨ ਬਾਕਸ ਡਿਲਕਸ',
    'FAN REGULATOR': 'ਫੈਨ ਰੈਗੂਲੇਟਰ',
    'Search all products...': 'ਸਾਰੇ ਪ੍ਰੋਡਕਟ ਖੋਜੋ...',
    'Filter products': 'ਪ੍ਰੋਡਕਟ ਫਿਲਟਰ ਕਰੋ',
    'Choose a category to see matching product names and items.': 'ਮਿਲਦੇ-ਜੁਲਦੇ ਪ੍ਰੋਡਕਟ ਨਾਮ ਅਤੇ ਆਈਟਮ ਵੇਖਣ ਲਈ ਕੋਈ ਕੈਟੇਗਰੀ ਚੁਣੋ।',
    Close: 'ਬੰਦ ਕਰੋ',
    products: 'ਪ੍ਰੋਡਕਟ',
    available: 'ਉਪਲਬਧ',
    result: 'ਨਤੀਜਾ',
    results: 'ਨਤੀਜੇ',
    'No results for': 'ਲਈ ਕੋਈ ਨਤੀਜਾ ਨਹੀਂ',
    'Try searching by product name or size': 'ਪ੍ਰੋਡਕਟ ਨਾਮ ਜਾਂ ਸਾਈਜ਼ ਨਾਲ ਖੋਜਣ ਦੀ ਕੋਸ਼ਿਸ਼ ਕਰੋ',
    'Tap card to view QR & details': 'QR ਅਤੇ ਵੇਰਵੇ ਵੇਖਣ ਲਈ ਕਾਰਡ ਟੈਪ ਕਰੋ',
    Name: 'ਨਾਮ',
    Code: 'ਕੋਡ',
    India: 'ਭਾਰਤ',
    Location: 'ਲੋਕੇਸ਼ਨ',
    'Business Details': 'ਬਿਜ਼ਨਸ ਵੇਰਵਾ',
    'Connected Dealer': 'ਜੁੜਿਆ ਡੀਲਰ',
    'SRV Profile Card': 'ਐਸਆਰਵੀ ਪ੍ਰੋਫਾਈਲ ਕਾਰਡ',
    'After selecting a photo, review it and tap Done to continue.': 'ਫੋਟੋ ਚੁਣਨ ਤੋਂ ਬਾਅਦ ਇਸਨੂੰ ਵੇਖੋ ਅਤੇ ਅੱਗੇ ਵੱਧਣ ਲਈ ਅਪਲੋਡ ਦਬਾਓ।',
    'If the crop looks right, tap Done to update your profile photo.': 'ਜੇ ਕ੍ਰਾਪ ਠੀਕ ਲੱਗਦਾ ਹੈ ਤਾਂ ਪ੍ਰੋਫਾਈਲ ਫੋਟੋ ਅਪਡੇਟ ਕਰਨ ਲਈ ਅਪਲੋਡ ਦਬਾਓ।',
    'Choose from camera or gallery, crop if needed, then finish with Done on the confirmation screen.': 'ਕੈਮਰਾ ਜਾਂ ਗੈਲਰੀ ਤੋਂ ਚੁਣੋ, ਫਿਰ ਕਨਫਰਮੇਸ਼ਨ ਸਕਰੀਨ ਤੇ Done ਦਬਾਓ।',
    'Are you sure you want to sign out?\nYour data will be saved.': 'ਕੀ ਤੁਸੀਂ ਯਕੀਨਨ ਲੌਗਆਉਟ ਕਰਨਾ ਚਾਹੁੰਦੇ ਹੋ?\nਤੁਹਾਡਾ ਡਾਟਾ ਸੇਵ ਰਹੇਗਾ।',
    'Invalid name': 'ਗਲਤ ਨਾਮ',
    'Name should contain only alphabets and spaces.': 'ਨਾਮ ਵਿੱਚ ਸਿਰਫ ਅੱਖਰ ਅਤੇ ਖਾਲੀ ਥਾਂ ਹੋਣੀਆਂ ਚਾਹੀਦੀਆਂ ਹਨ।',
    'Invalid phone number': 'ਗਲਤ ਫੋਨ ਨੰਬਰ',
    'Phone number should contain only integers.': 'ਫੋਨ ਨੰਬਰ ਵਿੱਚ ਸਿਰਫ ਅੰਕ ਹੋਣੇ ਚਾਹੀਦੇ ਹਨ।',
    'Invalid email': 'ਗਲਤ ਈਮੇਲ',
    'Please enter a valid email address.': 'ਕਿਰਪਾ ਕਰਕੇ ਸਹੀ ਈਮੇਲ ਪਤਾ ਦਰਜ ਕਰੋ।',
    'Invalid city': 'ਗਲਤ ਸ਼ਹਿਰ',
    'City should contain only alphabets and spaces.': 'ਸ਼ਹਿਰ ਦੇ ਨਾਮ ਵਿੱਚ ਸਿਰਫ ਅੱਖਰ ਅਤੇ ਖਾਲੀ ਥਾਂ ਹੋਣੀਆਂ ਚਾਹੀਦੀਆਂ ਹਨ।',
    'Invalid state': 'ਗਲਤ ਰਾਜ',
    'State should contain only alphabets and spaces.': 'ਰਾਜ ਦੇ ਨਾਮ ਵਿੱਚ ਸਿਰਫ ਅੱਖਰ ਅਤੇ ਖਾਲੀ ਥਾਂ ਹੋਣੀਆਂ ਚਾਹੀਦੀਆਂ ਹਨ।',
    'Invalid pincode': 'ਗਲਤ ਪਿੰਨਕੋਡ',
    'Pincode should contain only integers.': 'ਪਿੰਨਕੋਡ ਵਿੱਚ ਸਿਰਫ ਅੰਕ ਹੋਣੇ ਚਾਹੀਦੇ ਹਨ।',
    'Invalid holder name': 'ਗਲਤ ਹੋਲਡਰ ਨਾਮ',
    'GST / PAN holder name should contain only alphabets and spaces.': 'GST / PAN ਹੋਲਡਰ ਨਾਮ ਵਿੱਚ ਸਿਰਫ ਅੱਖਰ ਅਤੇ ਖਾਲੀ ਥਾਂ ਹੋਣੀਆਂ ਚਾਹੀਦੀਆਂ ਹਨ।',
    'Permission needed': 'ਇਜਾਜ਼ਤ ਲੋੜੀਂਦੀ ਹੈ',
    'Allow camera access to update your profile photo.': 'ਪ੍ਰੋਫਾਈਲ ਫੋਟੋ ਅਪਡੇਟ ਕਰਨ ਲਈ ਕੈਮਰਾ ਐਕਸੈੱਸ ਦੀ ਇਜਾਜ਼ਤ ਦਿਓ।',
    'Allow gallery access to update your profile photo.': 'ਪ੍ਰੋਫਾਈਲ ਫੋਟੋ ਅਪਡੇਟ ਕਰਨ ਲਈ ਗੈਲਰੀ ਐਕਸੈੱਸ ਦੀ ਇਜਾਜ਼ਤ ਦਿਓ।',
    'Unable to update photo': 'ਫੋਟੋ ਅਪਡੇਟ ਨਹੀਂ ਹੋ ਸਕੀ',
    'Please try again.': 'ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
    'Redeem Product': 'ਰੀਡੀਮ ਪ੍ਰੋਡਕਟ',
    'Lifetime Redeem': 'ਲਾਈਫਟਾਈਮ ਰੀਡੀਮ',
    'Redeemable Points': 'ਰੀਡੀਮ ਕੀਤੇ ਜਾ ਸਕਣ ਵਾਲੇ ਪੁਆਇੰਟ',
    Filter: 'ਫਿਲਟਰ',
    'Buy Schemes': 'ਸਕੀਮਾਂ ਖਰੀਦੋ',
    'Premium offers': 'ਪ੍ਰੀਮੀਅਮ ਆਫਰ',
    'Send to dealer': 'ਡੀਲਰ ਨੂੰ ਭੇਜੋ',
    'Transfer Point': 'ਪੁਆਇੰਟ ਟ੍ਰਾਂਸਫਰ',
    'This Month': 'ਇਸ ਮਹੀਨੇ',
    'Last 30 Days': 'ਪਿਛਲੇ 30 ਦਿਨ',
    Processed: 'ਪ੍ਰੋਸੈਸਡ',
    Completed: 'ਪੂਰਾ ਹੋਇਆ',
    Success: 'ਸਫਲ',
    Credited: 'ਜਮਾ ਹੋਇਆ',
    'Premium Fan Box Scheme': 'ਪ੍ਰੀਮੀਅਮ ਫੈਨ ਬਾਕਸ ਸਕੀਮ',
    'Bank Transfer Request': 'ਬੈਂਕ ਟ੍ਰਾਂਸਫਰ ਬੇਨਤੀ',
    'Points Sent to Dealer': 'ਡੀਲਰ ਨੂੰ ਭੇਜੇ ਪੁਆਇੰਟ',
    '5% bonus from electrician redemptions': 'ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ ਰਿਡੈਂਪਸ਼ਨ ਤੋਂ 5% ਬੋਨਸ',
    'Festival Reward Scheme': 'ਤਿਉਹਾਰੀ ਰਿਵਾਰਡ ਸਕੀਮ',
    Hot: 'ਹਾਟ',
    New: 'ਨਵਾਂ',
    Live: 'ਲਾਈਵ',
    'Festive Bonus': 'ਤਿਉਹਾਰੀ ਬੋਨਸ',
    'Dealer Growth Offer': 'ਡੀਲਰ ਗ੍ਰੋਥ ਆਫਰ',
    'Scan & Win': 'ਸਕੈਨ ਅਤੇ ਜਿੱਤੋ',
    'Get 500 extra points on selected premium range purchases.': 'ਚੁਣੀ ਹੋਈ ਪ੍ਰੀਮੀਅਮ ਰੇਂਜ ਖਰੀਦ ' + 'ਤੇ 500 ਵਾਧੂ ਪੁਆਇੰਟ ਪਾਓ।',
    'Complete your monthly target and unlock a surprise gift slab.': 'ਆਪਣਾ ਮਹੀਨਾਵਾਰ ਟਾਰਗੇਟ ਪੂਰਾ ਕਰੋ ਅਤੇ ਸਰਪ੍ਰਾਇਜ਼ ਗਿਫਟ ਸਲੈਬ ਅਨਲੌਕ ਕਰੋ।',
    'Scan 25 products this month to get accelerated reward points.': 'ਇਸ ਮਹੀਨੇ 25 ਪ੍ਰੋਡਕਟ ਸਕੈਨ ਕਰਕੇ ਤੇਜ਼ ਰਿਵਾਰਡ ਪੁਆਇੰਟ ਪਾਓ।',
    'Enter amount': 'ਰਕਮ ਦਰਜ ਕਰੋ',
    'Please enter a valid withdrawal amount.': 'ਕਿਰਪਾ ਕਰਕੇ ਠੀਕ ਨਿਕਾਸੀ ਰਕਮ ਦਰਜ ਕਰੋ।',
    'Insufficient balance': 'ਪਰਯਾਪਤ ਬੈਲੈਂਸ ਨਹੀਂ',
    'Withdrawal amount cannot be more than your available dealer bonus.': 'ਨਿਕਾਸੀ ਰਕਮ ਤੁਹਾਡੇ ਉਪਲਬਧ ਡੀਲਰ ਬੋਨਸ ਤੋਂ ਵੱਧ ਨਹੀਂ ਹੋ ਸਕਦੀ।',
    'Request submitted': 'ਬੇਨਤੀ ਭੇਜ ਦਿੱਤੀ ਗਈ',
    'Rs. 250 will be transferred to your bank account after approval.': 'ਮੰਜ਼ੂਰੀ ਤੋਂ ਬਾਅਦ Rs. 250 ਤੁਹਾਡੇ ਬੈਂਕ ਖਾਤੇ ਵਿੱਚ ਭੇਜੇ ਜਾਣਗੇ।',
    'Rs. 500 will be transferred to your bank account after approval.': 'ਮੰਜ਼ੂਰੀ ਤੋਂ ਬਾਅਦ Rs. 500 ਤੁਹਾਡੇ ਬੈਂਕ ਖਾਤੇ ਵਿੱਚ ਭੇਜੇ ਜਾਣਗੇ।',
    'Rs. 1000 will be transferred to your bank account after approval.': 'ਮੰਜ਼ੂਰੀ ਤੋਂ ਬਾਅਦ Rs. 1000 ਤੁਹਾਡੇ ਬੈਂਕ ਖਾਤੇ ਵਿੱਚ ਭੇਜੇ ਜਾਣਗੇ।',
    '5% Auto Bonus': '5% ਆਟੋ ਬੋਨਸ',
    'GET YOUR BONUS': 'ਆਪਣਾ ਬੋਨਸ ਲਵੋ',
    '5% of the points redeemed by any electrician will be credited to your dealer wallet. 1 point = 1 INR, and you can withdraw it directly to your bank account.': 'ਕਿਸੇ ਵੀ ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ ਵੱਲੋਂ ਰਿਡੀਮ ਕੀਤੇ ਪੁਆਇੰਟਾਂ ਦਾ 5% ਤੁਹਾਡੇ ਡੀਲਰ ਵਾਲਿਟ ਵਿੱਚ ਜਮਾ ਹੋਵੇਗਾ। 1 ਪੁਆਇੰਟ = 1 INR, ਅਤੇ ਤੁਸੀਂ ਇਸਨੂੰ ਸਿੱਧਾ ਆਪਣੇ ਬੈਂਕ ਖਾਤੇ ਵਿੱਚ ਨਿਕਾਲ ਸਕਦੇ ਹੋ।',
    'Available to withdraw': 'ਨਿਕਾਸੀ ਲਈ ਉਪਲਬਧ',
    '1 Point = 1 INR': '1 ਪੁਆਇੰਟ = 1 INR',
    'Active electricians': 'ਸਕ੍ਰਿਆ ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ',
    'Monthly redeemed pts': 'ਮਹੀਨਾਵਾਰ ਰਿਡੀਮ ਪੁਆਇੰਟ',
    'This month bonus': 'ਇਸ ਮਹੀਨੇ ਦਾ ਬੋਨਸ',
    'How it works': 'ਇਹ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ',
    'Electrician points redeem hote hi 5% dealer bonus auto-credit ho jata hai.': 'ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ ਦੇ ਪੁਆਇੰਟ ਰਿਡੀਮ ਹੁੰਦੇ ਹੀ 5% ਡੀਲਰ ਬੋਨਸ ਆਪਣੇ ਆਪ ਜਮਾ ਹੋ ਜਾਂਦਾ ਹੈ।',
    'Bonus balance update hota rahega and 1 point ki value 1 INR rahegi.': 'ਬੋਨਸ ਬੈਲੈਂਸ ਅਪਡੇਟ ਹੁੰਦਾ ਰਹੇਗਾ ਅਤੇ 1 ਪੁਆਇੰਟ ਦੀ ਕੀਮਤ 1 INR ਰਹੇਗੀ।',
    'Aap bank transfer request karke amount withdraw kar sakte hain.': 'ਤੁਸੀਂ ਬੈਂਕ ਟ੍ਰਾਂਸਫਰ ਬੇਨਤੀ ਕਰਕੇ ਰਕਮ ਨਿਕਾਲ ਸਕਦੇ ਹੋ।',
    'Withdraw to bank': 'ਬੈਂਕ ਵਿੱਚ ਨਿਕਾਸੀ',
    'Transfer to ICICI Bank ending 2048': 'ICICI Bank ending 2048 ਵਿੱਚ ਟ੍ਰਾਂਸਫਰ',
    'Enter amount in rupees': 'ਰੁਪਏ ਵਿੱਚ ਰਕਮ ਦਰਜ ਕਰੋ',
    'Request bank transfer': 'ਬੈਂਕ ਟ੍ਰਾਂਸਫਰ ਬੇਨਤੀ ਕਰੋ',
    'Recent bonus activity': 'ਹਾਲੀਆ ਬੋਨਸ ਗਤੀਵਿਧੀ',
    Redeemed: 'ਰਿਡੀਮ ਕੀਤਾ',
    'Active Orders': 'ਸਰਗਰਮ ਆਰਡਰ',
    'Last Delivery': 'ਆਖਰੀ ਡਿਲੀਵਰੀ',
    'Scan & Transfer': 'ਸਕੈਨ ਅਤੇ ਟ੍ਰਾਂਸਫਰ',
    'Scan any SRV product QR to transfer points to dealers instantly.': 'SRV ਪ੍ਰੋਡਕਟ QR ਸਕੈਨ ਕਰਕੇ ਤੁਰੰਤ ਡੀਲਰ ਨੂੰ ਪੁਆਇੰਟ ਟ੍ਰਾਂਸਫਰ ਕਰੋ।',
    'Open Scanner': 'ਸਕੈਨਰ ਖੋਲ੍ਹੋ',
    pts: 'ਪੁਆਇੰਟ',
    'Today, 11:40 AM': 'ਅੱਜ, 11:40 AM',
    'Yesterday, 06:15 PM': 'ਕੱਲ੍ਹ, 06:15 PM',
    '05 Apr 2026': '05 ਅਪ੍ਰੈਲ 2026',
    'Dealer Calling Desk': 'ਡੀਲਰ ਕਾਲਿੰਗ ਡੈਸਕ',
    'Reach your electricians instantly': 'ਆਪਣੇ ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨਾਂ ਨਾਲ ਤੁਰੰਤ ਜੁੜੋ',
    'Use normal phone call or WhatsApp call actions to connect with any associated electrician.': 'ਕਿਸੇ ਵੀ ਜੁੜੇ ਹੋਏ ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ ਨਾਲ ਸੰਪਰਕ ਕਰਨ ਲਈ ਆਮ ਕਾਲ ਜਾਂ ਵਟਸਐਪ ਕਾਲ ਐਕਸ਼ਨ ਵਰਤੋ।',
    'Choose App Language': 'ਐਪ ਭਾਸ਼ਾ ਚੁਣੋ',
    'Switch any time from App Settings': 'ਕਦੇ ਵੀ App Settings ਤੋਂ ਬਦਲੋ',
    'verification successfully done.': 'ਵੇਰੀਫਿਕੇਸ਼ਨ ਸਫਲਤਾਪੂਰਵਕ ਹੋ ਗਿਆ।',
    Silver: 'ਸਿਲਵਰ',
    Gold: 'ਗੋਲਡ',
    Platinum: 'ਪਲੈਟਿਨਮ',
    Diamond: 'ਡਾਇਮੰਡ',
    Member: 'ਮੈਂਬਰ',
    Current: 'ਮੌਜੂਦਾ',
    'Current Reward Level': 'ਮੌਜੂਦਾ ਰਿਵਾਰਡ ਲੈਵਲ',
    'Your electrician grading is based on total reward points earned through scans and redemptions.': 'ਤੁਹਾਡੀ ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ ਗ੍ਰੇਡਿੰਗ ਸਕੈਨ ਅਤੇ ਰਿਡੈਂਪਸ਼ਨ ਰਾਹੀਂ ਕਮਾਏ ਕੁੱਲ ਰਿਵਾਰਡ ਪੁਆਇੰਟਾਂ ਉੱਤੇ ਅਧਾਰਿਤ ਹੈ।',
    'Current points': 'ਮੌਜੂਦਾ ਪੁਆਇੰਟ',
    'Tier range': 'ਟੀਅਰ ਰੇਂਜ',
    'Points grading system': 'ਪੁਆਇੰਟ ਗ੍ਰੇਡਿੰਗ ਸਿਸਟਮ',
    '0 - 1000 points': '0 - 1000 ਪੁਆਇੰਟ',
    '1001 - 5000 points': '1001 - 5000 ਪੁਆਇੰਟ',
    '5001 - 10000 points': '5001 - 10000 ਪੁਆਇੰਟ',
    '10000+ points': '10000+ ਪੁਆਇੰਟ',
    'Starting level for electricians building up their first reward points.': 'ਆਪਣੇ ਪਹਿਲੇ ਰਿਵਾਰਡ ਪੁਆਇੰਟ ਬਣਾਉਣ ਵਾਲੇ ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨਾਂ ਲਈ ਸ਼ੁਰੂਆਤੀ ਪੱਧਰ।',
    'Strong reward status with steady scanning and reward collection.': 'ਨਿਯਮਿਤ ਸਕੈਨਿੰਗ ਅਤੇ ਰਿਵਾਰਡ ਇਕੱਠਾ ਕਰਨ ਨਾਲ ਮਜ਼ਬੂਤ ਰਿਵਾਰਡ ਸਥਿਤੀ।',
    'Premium level for electricians with high reward point activity.': 'ਉੱਚ ਰਿਵਾਰਡ ਪੁਆਇੰਟ ਗਤੀਵਿਧੀ ਵਾਲੇ ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨਾਂ ਲਈ ਪ੍ਰੀਮਿਯਮ ਪੱਧਰ।',
    'Top elite reward level for electricians with the strongest point balance.': 'ਸਭ ਤੋਂ ਮਜ਼ਬੂਤ ਪੁਆਇੰਟ ਬੈਲੈਂਸ ਵਾਲੇ ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨਾਂ ਲਈ ਸਭ ਤੋਂ ਉੱਚਾ ਐਲੀਟ ਰਿਵਾਰਡ ਪੱਧਰ।',
    'Dealer Network': 'ਡੀਲਰ ਨੈੱਟਵਰਕ',
    'Connected electricians': 'ਜੁੜੇ ਹੋਏ ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ',
    'Dealers can review every connected electrician here and add new electricians to their network from the same page.': 'ਡੀਲਰ ਇੱਥੇ ਆਪਣੇ ਸਾਰੇ ਜੁੜੇ ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ ਵੇਖ ਸਕਦੇ ਹਨ ਅਤੇ ਇਸੇ ਪੇਜ ਤੋਂ ਨਵੇਂ ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ ਜੋੜ ਸਕਦੇ ਹਨ।',
    'Add Electrician': 'ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ ਜੋੜੋ',
    Active: 'ਸਕ੍ਰਿਆ',
    Pending: 'ਬਕਾਇਆ',
    records: 'ਰਿਕਾਰਡ',
    'Search by name, phone, or city': 'ਨਾਮ, ਫੋਨ ਜਾਂ ਸ਼ਹਿਰ ਨਾਲ ਖੋਜੋ',
    'Electrician directory': 'ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ ਡਾਇਰੈਕਟਰੀ',
    'Add electrician': 'ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ ਜੋੜੋ',
    'Verify the number first, then complete the remaining details.': 'ਪਹਿਲਾਂ ਨੰਬਰ ਵੇਰੀਫਾਈ ਕਰੋ, ਫਿਰ ਬਾਕੀ ਵੇਰਵੇ ਭਰੋ।',
    'Electrician name': 'ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ ਦਾ ਨਾਮ',
    'Enter full name': 'ਪੂਰਾ ਨਾਮ ਦਰਜ ਕਰੋ',
    'Electrician number': 'ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ ਨੰਬਰ',
    '10-digit mobile number': '10 ਅੰਕਾਂ ਦਾ ਮੋਬਾਈਲ ਨੰਬਰ',
    'OTP sent to +91': '+91 ਤੇ OTP ਭੇਜਿਆ ਗਿਆ',
    'Demo OTP': 'ਡੈਮੋ OTP',
    'Enter OTP': 'OTP ਦਰਜ ਕਰੋ',
    Confirm: 'ਕਨਫਰਮ',
    'Phone number verified successfully': 'ਫੋਨ ਨੰਬਰ ਸਫਲਤਾਪੂਰਵਕ ਵੇਰੀਫਾਈ ਹੋ ਗਿਆ',
    'City or district': 'ਸ਼ਹਿਰ ਜਾਂ ਜ਼ਿਲ੍ਹਾ',
    'Invalid OTP': 'ਗਲਤ OTP',
    'Please enter the correct 4-digit OTP to verify the phone number.': 'ਫੋਨ ਨੰਬਰ ਵੇਰੀਫਾਈ ਕਰਨ ਲਈ ਸਹੀ 4 ਅੰਕਾਂ ਵਾਲਾ OTP ਦਰਜ ਕਰੋ।',
    'Connected today': 'ਅੱਜ ਜੁੜੇ',
    'Connected 3 days ago': '3 ਦਿਨ ਪਹਿਲਾਂ ਜੁੜੇ',
    'Invite pending': 'ਨਿਮੰਤਰਣ ਬਕਾਇਆ',
    'Notification Center': 'ਨੋਟੀਫਿਕੇਸ਼ਨ ਸੈਂਟਰ',
    'Stay updated with SRV': 'SRV ਨਾਲ ਅਪਡੇਟ ਰਹੋ',
    'Important price updates, reward alerts, and account notices in one place.': 'ਮਹੱਤਵਪੂਰਨ ਪ੍ਰਾਈਸ ਅਪਡੇਟ, ਰਿਵਾਰਡ ਅਲਰਟ ਅਤੇ ਅਕਾਊਂਟ ਨੋਟਿਸ ਇੱਕ ਥਾਂ।',
    'Back Home': 'ਘਰ ਵਾਪਸ',
    'More': 'ਹੋਰ',
    'Latest updates': 'ਤਾਜ਼ਾ ਅਪਡੇਟ',
    new: 'ਨਵੇਂ',
    'Price Update': 'ਪ੍ਰਾਈਸ ਅਪਡੇਟ',
    'The price of 4 way DD has been updated to Rs.306.': '4 ਵੇ ਡੀਡੀ ਦੀ ਕੀਮਤ ਹੁਣ Rs.306 ਕਰ ਦਿੱਤੀ ਗਈ ਹੈ।',
    '2 hr ago': '2 ਘੰਟੇ ਪਹਿਲਾਂ',
    'Price Alert': 'ਪ੍ਰਾਈਸ ਅਲਰਟ',
    'The price of 6 Way DD has been updated to Rs.363.': '6 ਵੇ ਡੀਡੀ ਦੀ ਕੀਮਤ ਹੁਣ Rs.363 ਕਰ ਦਿੱਤੀ ਗਈ ਹੈ।',
    '3 hr ago': '3 ਘੰਟੇ ਪਹਿਲਾਂ',
    'Scheme Notice': 'ਸਕੀਮ ਨੋਟਿਸ',
    'Selected SRV reward schemes have updated slabs for this week.': 'ਇਸ ਹਫ਼ਤੇ ਲਈ ਚੁਣੀਆਂ ਗਈਆਂ SRV ਰਿਵਾਰਡ ਸਕੀਮਾਂ ਦੇ ਸਲੈਬ ਅਪਡੇਟ ਹੋ ਗਏ ਹਨ।',
    Rewards: 'ਰਿਵਾਰਡ',
    'Important SRV announcement': 'ਮਹੱਤਵਪੂਰਨ SRV ਐਲਾਨ',
    'Keep your profile and bank details updated for smooth redemptions and withdrawals.': 'ਸੁਚਾਰੂ ਰਿਡੈਂਪਸ਼ਨ ਅਤੇ ਨਿਕਾਸੀ ਲਈ ਆਪਣੀ ਪ੍ਰੋਫਾਈਲ ਅਤੇ ਬੈਂਕ ਵੇਰਵਾ ਅਪਡੇਟ ਰੱਖੋ।',
    Alerts: 'ਅਲਰਟ',
    Today: 'ਅੱਜ',
    'Added just now': 'ਹੁਣੇ ਜੋੜਿਆ ਗਿਆ',
    'Capture a photo, crop it if needed, then confirm it on the next screen': 'ਫੋਟੋ ਖਿੱਚੋ, ਫਿਰ ਅਗਲੀ ਸਕਰੀਨ ਤੇ ਕਨਫਰਮ ਕਰੋ',
    'Select a photo, crop it if needed, then confirm it on the next screen': 'ਫੋਟੋ ਚੁਣੋ, ਫਿਰ ਅਗਲੀ ਸਕਰੀਨ ਤੇ ਕਨਫਰਮ ਕਰੋ',
    'Scan QR Code': 'QR ਕੋਡ ਸਕੈਨ ਕਰੋ',
    'Point camera at the QR sticker\non any SRV product box': 'ਕਿਸੇ ਵੀ SRV ਪ੍ਰੋਡਕਟ ਬਾਕਸ ਉੱਤੇ ਲੱਗੇ QR ਸਟਿਕਰ ਵੱਲ ਕੈਮਰਾ ਰੱਖੋ',
    'Camera access allow karo taaki aap QR scan kar sako.': 'QR ਸਕੈਨ ਕਰਨ ਲਈ ਕੈਮਰਾ ਐਕਸੈੱਸ ਦਿਓ।',
    'Gallery access allow karo taaki aap QR image select kar sako.': 'QR ਤਸਵੀਰ ਚੁਣਨ ਲਈ ਗੈਲਰੀ ਐਕਸੈੱਸ ਦਿਓ।',
    'Align QR code within the frame': 'QR ਕੋਡ ਨੂੰ ਫਰੇਮ ਦੇ ਅੰਦਰ ਰੱਖੋ',
    'QR Code detected': 'QR ਕੋਡ ਮਿਲ ਗਿਆ',
    'SRV MCB 32A detected': 'SRV MCB 32A ਮਿਲ ਗਿਆ',
    'You earned +80 reward points.': 'ਤੁਸੀਂ +80 ਰਿਵਾਰਡ ਪੌਇੰਟ ਕਮਾਏ ਹਨ।',
    'Claim Points & Continue': 'ਪੌਇੰਟ ਕਲੇਮ ਕਰੋ ਅਤੇ ਅੱਗੇ ਵਧੋ',
    'Scanning...': 'ਸਕੈਨ ਹੋ ਰਿਹਾ ਹੈ...',
    'Start Scanning': 'ਸਕੈਨ ਸ਼ੁਰੂ ਕਰੋ',
    Flashlight: 'ਫਲੈਸ਼ਲਾਈਟ',
    'Flashlight On': 'ਫਲੈਸ਼ਲਾਈਟ ਚਾਲੂ',
    Gallery: 'ਗੈਲਰੀ',
    'How to Scan': 'ਸਕੈਨ ਕਿਵੇਂ ਕਰਨਾ ਹੈ',
    'Look for the QR code sticker on your SRV product box.': 'ਆਪਣੇ SRV ਪ੍ਰੋਡਕਟ ਬਾਕਸ ਉੱਤੇ QR ਕੋਡ ਸਟਿਕਰ ਲੱਭੋ।',
    'Place the code inside the frame and keep the phone steady.': 'ਕੋਡ ਨੂੰ ਫਰੇਮ ਦੇ ਅੰਦਰ ਰੱਖੋ ਅਤੇ ਫੋਨ ਨੂੰ ਅਡੋਲ ਰੱਖੋ।',
    'Claim the points and continue to your dashboard.': 'ਪੌਇੰਟ ਕਲੇਮ ਕਰੋ ਅਤੇ ਆਪਣੇ ਡੈਸ਼ਬੋਰਡ ਤੇ ਜਾਓ।',
    '+120 this week': '+120 ਇਸ ਹਫ਼ਤੇ',
    'Rs 100 Cashback': 'Rs 100 ਕੈਸ਼ਬੈਕ',
    'Direct UPI or bank transfer': 'ਸਿੱਧਾ UPI ਜਾਂ ਬੈਂਕ ਟ੍ਰਾਂਸਫਰ',
    'Amazon Voucher': 'ਅਮੇਜ਼ਾਨ ਵਾਊਚਰ',
    'Rs 200 gift card code': 'Rs 200 ਗਿਫਟ ਕਾਰਡ ਕੋਡ',
    'SRV Product Bundle': 'SRV ਪ੍ਰੋਡਕਟ ਬੰਡਲ',
    'Free kit worth Rs 500': 'Rs 500 ਦੀ ਮੁਫ਼ਤ ਕਿੱਟ',
    'Paytm Voucher': 'Paytm ਵਾਊਚਰ',
    'Rs 150 wallet credit': 'Rs 150 ਵਾਲਿਟ ਕਰੈਡਿਟ',
    'Premium Toolkit': 'ਪ੍ਰੀਮਿਯਮ ਟੂਲਕਿਟ',
    'Professional electrician kit': 'ਪ੍ਰੋਫੈਸ਼ਨਲ ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ ਕਿੱਟ',
    'Flipkart Voucher': 'ਫਲਿਪਕਾਰਟ ਵਾਊਚਰ',
    'Rs 300 shopping voucher': 'Rs 300 ਸ਼ਾਪਿੰਗ ਵਾਊਚਰ',
    'Elegant activity timeline': 'ਸੁੰਦਰ ਗਤੀਵਿਧੀ ਟਾਈਮਲਾਈਨ',
    'Referral reward credited': 'ਰੈਫਰਲ ਰਿਵਾਰਡ ਜਮਾ ਹੋਇਆ',
    'Bank transfer processed': 'ਬੈਂਕ ਟ੍ਰਾਂਸਫਰ ਹੋ ਗਿਆ',
    'Scheme bonus unlocked': 'ਸਕੀਮ ਬੋਨਸ ਅਨਲੌਕ ਹੋਇਆ',
    'SRV Dealer Wallet': 'SRV ਡੀਲਰ ਵਾਲਿਟ',
    'Dealer wallet for schemes, bank payouts, and dealer bonus tracking.': 'ਸਕੀਮਾਂ, ਬੈਂਕ ਪੇਆਊਟ ਅਤੇ ਡੀਲਰ ਬੋਨਸ ਟ੍ਰੈਕਿੰਗ ਲਈ ਡੀਲਰ ਵਾਲਿਟ।',
    'Active Electricians': 'ਸਕ੍ਰਿਆ ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ',
    'Bonus Withdrawals': 'ਬੋਨਸ ਨਿਕਾਸੀ',
    'Quick Actions': 'ਤੁਰੰਤ ਐਕਸ਼ਨ',
    'Manage dealer payouts': 'ਡੀਲਰ ਪੇਆਊਟ ਸੰਭਾਲੋ',
    'Redeem Point History': 'ਰਿਡੀਮ ਪੁਆਇੰਟ ਹਿਸਟਰੀ',
    'No detailed records yet': 'ਹਾਲੇ ਤੱਕ ਕੋਈ ਵਿਸਤ੍ਰਿਤ ਰਿਕਾਰਡ ਨਹੀਂ',
    'Activity Timeline': 'ਗਤੀਵਿਧੀ ਟਾਈਮਲਾਈਨ',
    'Your complete wallet history will appear here once bank payouts or dealer bonus activity starts.': 'ਜਿਵੇਂ ਹੀ ਬੈਂਕ ਪੇਆਊਟ ਜਾਂ ਡੀਲਰ ਬੋਨਸ ਗਤੀਵਿਧੀ ਸ਼ੁਰੂ ਹੋਵੇਗੀ, ਇੱਥੇ ਤੁਹਾਡੀ ਪੂਰੀ ਵਾਲਿਟ ਹਿਸਟਰੀ ਦਿਖਾਈ ਦੇਵੇਗੀ।',
    'Your complete wallet history will appear here once redemption or transfer activity starts.': 'ਜਿਵੇਂ ਹੀ ਰਿਡੈਂਪਸ਼ਨ ਜਾਂ ਟ੍ਰਾਂਸਫਰ ਗਤੀਵਿਧੀ ਸ਼ੁਰੂ ਹੋਵੇਗੀ, ਇੱਥੇ ਤੁਹਾਡੀ ਪੂਰੀ ਵਾਲਿਟ ਹਿਸਟਰੀ ਦਿਖਾਈ ਦੇਵੇਗੀ।',
    'Premium rewards dashboard for redemptions, transfers, and loyalty growth.': 'ਰਿਡੈਂਪਸ਼ਨ, ਟ੍ਰਾਂਸਫਰ ਅਤੇ ਲਾਇਲਟੀ ਵਿਕਾਸ ਲਈ ਪ੍ਰੀਮੀਅਮ ਰਿਵਾਰਡ ਡੈਸ਼ਬੋਰਡ।',
    'Bank Transfer': 'ਬੈਂਕ ਟ੍ਰਾਂਸਫਰ',
    'Fast withdrawal': 'ਤੇਜ਼ ਨਿਕਾਸੀ',
    'Dealer Bonus': 'ਡੀਲਰ ਬੋਨਸ',
    '5% electrician bonus': '5% ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ ਬੋਨਸ',
    'Today, 10:42 AM': 'ਅੱਜ, 10:42 AM',
    'Yesterday, 06:20 PM': 'ਕੱਲ੍ਹ, 06:20 PM',
    '02 Apr 2026': '02 ਅਪ੍ਰੈਲ 2026',
    'Move your wallet faster': 'ਆਪਣੇ ਵਾਲਿਟ ਨੂੰ ਤੇਜ਼ੀ ਨਾਲ ਭੇਜੋ',
    'Redemption History': 'ਰਿਡੈਂਪਸ਼ਨ ਹਿਸਟਰੀ',
    'Rewards Store': 'ਰਿਵਾਰਡ ਸਟੋਰ',
  },
} as const;

export const translateUiText = (language: AppLanguage, text: string) => {
  const translated = uiText[language]?.[text];
  if (!translated || hasCorruptedText(translated)) {
    return text;
  }
  return translated;
};

export const formatCountText = (
  language: AppLanguage,
  count: number,
  english: string,
  hindi: string,
  punjabi: string
) => {
  const unit = language === 'Hindi' ? hindi : language === 'Punjabi' ? punjabi : english;
  return `${count} ${unit}`;
};

export type ThemePalette = {
  bg: string; surface: string; soft: string; border: string; textPrimary: string; textSecondary: string; textMuted: string; heroSurface: string; heroStrip: string;
};

export const getThemePalette = (isDark: boolean): ThemePalette => ({
  bg: isDark ? '#0B1220' : C.bg,
  surface: isDark ? '#111827' : C.surface,
  soft: isDark ? '#1F2937' : C.bg,
  border: isDark ? '#243043' : C.border,
  textPrimary: isDark ? '#F8FAFC' : C.dark,
  textSecondary: isDark ? '#D0D9E8' : C.mid,
  textMuted: isDark ? '#94A3B8' : C.muted,
  heroSurface: isDark ? '#111827' : C.surface,
  heroStrip: isDark ? '#0F172A' : '#FCFCFE',
});

export type PreferenceContextValue = {
  language: AppLanguage;
  setLanguage: (language: AppLanguage) => void;
  darkMode: boolean;
  setDarkMode: (enabled: boolean) => void;
  t: (key: keyof (typeof translations)['English']) => string;
  tx: (text: string) => string;
  theme: ThemePalette;
};

export const PreferenceContext = createContext<PreferenceContextValue | null>(null);
export function usePreferenceContext() {
  const value = useContext(PreferenceContext);
  if (!value) throw new Error('PreferenceContext missing');
  return value;
}

export function AppIcon({ name, size = 18, color = '#0F1120', strokeWidth = 1.8 }: { name: IconName; size?: number; color?: string; strokeWidth?: number }) {
  switch (name) {
    case 'edit': return <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"><Path d="M4 20l4.2-1 9.1-9.1a2.2 2.2 0 10-3.1-3.1L5.1 15.9 4 20z" stroke={color} strokeWidth={strokeWidth} strokeLinejoin="round" /><Path d="M13 8l3 3" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" /></Svg>;
    case 'eye': return <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"><Path d="M2.5 12s3.3-5 9.5-5 9.5 5 9.5 5-3.3 5-9.5 5-9.5-5-9.5-5z" stroke={color} strokeWidth={strokeWidth} strokeLinejoin="round" /><Circle cx="12" cy="12" r="3" stroke={color} strokeWidth={strokeWidth} /></Svg>;
    case 'eyeOff': return <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"><Path d="M3 3l18 18" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" /><Path d="M10.6 5.2c.5-.1.9-.2 1.4-.2 6.2 0 9.5 5 9.5 5a15.5 15.5 0 01-3.4 3.6M6.3 6.3A15.7 15.7 0 002.5 12s3.3 5 9.5 5c1 0 1.9-.1 2.7-.4" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" /><Path d="M9.9 9.9A3 3 0 0014.1 14.1" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" /></Svg>;
    case 'star': return <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"><Path d="M12 3.5l2.7 5.5 6.1.9-4.4 4.3 1 6.1-5.4-2.8-5.4 2.8 1-6.1-4.4-4.3 6.1-.9L12 3.5z" stroke={color} strokeWidth={strokeWidth} strokeLinejoin="round" /></Svg>;
    case 'scan': return <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"><Rect x="4" y="4" width="6" height="6" rx="1.3" stroke={color} strokeWidth={strokeWidth} /><Rect x="14" y="4" width="6" height="6" rx="1.3" stroke={color} strokeWidth={strokeWidth} /><Rect x="4" y="14" width="6" height="6" rx="1.3" stroke={color} strokeWidth={strokeWidth} /><Path d="M14 14h2v2h-2zM18 14h2v6h-6v-2h4v-4z" fill={color} /></Svg>;
    case 'gift': return <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"><Rect x="3" y="8" width="18" height="4" rx="1.2" stroke={color} strokeWidth={strokeWidth} /><Path d="M19 12v7a2 2 0 01-2 2H7a2 2 0 01-2-2v-7" stroke={color} strokeWidth={strokeWidth} /><Path d="M12 8v13M12 8C12 8 9.5 6.1 9.5 4.7a2.5 2.5 0 015 0C14.5 6.1 12 8 12 8z" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" /></Svg>;
    case 'redeem': return <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"><Path d="M7 6.5h10a2 2 0 012 2v3.5c0 4.1-2.7 7.2-7 8.5-4.3-1.3-7-4.4-7-8.5V8.5a2 2 0 012-2z" stroke={color} strokeWidth={strokeWidth} strokeLinejoin="round" /><Path d="M9 10.5l2 2 4-4" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" /><Path d="M9 4.5h6" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" /></Svg>;
    case 'signOut': return <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"><Path d="M10 5H6a2 2 0 00-2 2v10a2 2 0 002 2h4" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" /><Path d="M14 8l4 4-4 4M8 12h10" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" /></Svg>;
    case 'transfer': return <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"><Path d="M7 7h12M15 3l4 4-4 4M17 17H5M9 13l-4 4 4 4" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" /></Svg>;
    case 'order': return <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"><Path d="M4 7l8-4 8 4-8 4-8-4zM4 7v10l8 4 8-4V7" stroke={color} strokeWidth={strokeWidth} strokeLinejoin="round" /><Path d="M12 11v10" stroke={color} strokeWidth={strokeWidth} /></Svg>;
    case 'bank': return <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"><Path d="M3 9l9-5 9 5" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" /><Path d="M5 10v8M10 10v8M14 10v8M19 10v8M3 20h18" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" /></Svg>;
    case 'refer': return <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"><Circle cx="8" cy="8" r="3" stroke={color} strokeWidth={strokeWidth} /><Circle cx="16.5" cy="7" r="2.5" stroke={color} strokeWidth={strokeWidth} /><Path d="M3.5 18a4.5 4.5 0 019 0M13 17a3.5 3.5 0 017 0" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" /></Svg>;
    case 'help': return <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"><Circle cx="12" cy="12" r="9" stroke={color} strokeWidth={strokeWidth} /><Path d="M9.5 9a2.5 2.5 0 115 0c0 1.8-2.5 2.1-2.5 4" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" /><Circle cx="12" cy="17.2" r="0.8" fill={color} /></Svg>;
    case 'offer': return <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"><Path d="M20 12l-8 8-8-8 8-8 8 8z" stroke={color} strokeWidth={strokeWidth} strokeLinejoin="round" /><Circle cx="9" cy="9" r="1" fill={color} /><Path d="M10 14l4-4" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" /></Svg>;
    case 'notification': return <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"><Path d="M6 16.5V11a6 6 0 1112 0v5.5l1.2 1.2a.8.8 0 01-.57 1.36H5.37a.8.8 0 01-.57-1.36L6 16.5z" stroke={color} strokeWidth={strokeWidth} strokeLinejoin="round" /><Path d="M10 20a2 2 0 004 0" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" /></Svg>;
    case 'settings': return <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"><Circle cx="12" cy="12" r="3" stroke={color} strokeWidth={strokeWidth} /><Path d="M19.4 15a1 1 0 00.2 1.1l.1.1a2 2 0 010 2.8 2 2 0 01-2.8 0l-.1-.1a1 1 0 00-1.1-.2 1 1 0 00-.6.9V20a2 2 0 01-4 0v-.2a1 1 0 00-.6-.9 1 1 0 00-1.1.2l-.1.1a2 2 0 01-2.8 0 2 2 0 010-2.8l.1-.1a1 1 0 00.2-1.1 1 1 0 00-.9-.6H4a2 2 0 010-4h.2a1 1 0 00.9-.6 1 1 0 00-.2-1.1l-.1-.1a2 2 0 010-2.8 2 2 0 012.8 0l.1.1a1 1 0 001.1.2 1 1 0 00.6-.9V4a2 2 0 014 0v.2a1 1 0 00.6.9 1 1 0 001.1-.2l.1-.1a2 2 0 012.8 0 2 2 0 010 2.8l-.1.1a1 1 0 00-.2 1.1 1 1 0 00.9.6H20a2 2 0 010 4h-.2a1 1 0 00-.4.1z" stroke={color} strokeWidth={1.4} strokeLinecap="round" strokeLinejoin="round" /></Svg>;
    case 'history': return <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"><Path d="M4 4v5h5M20 12a8 8 0 10-2.3 5.7" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" /><Path d="M12 8v4l2.5 1.5" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" /></Svg>;
    case 'support': return <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"><Path d="M7 10a5 5 0 0110 0v1a2 2 0 012 2v2a2 2 0 01-2 2h-2v-4h2M7 13H5a2 2 0 00-2 2 2 2 0 002 2h2v-4z" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" /><Path d="M12 19h2.5a2 2 0 002-2" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" /></Svg>;
    case 'camera': return <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"><Rect x="3" y="6" width="18" height="14" rx="3" stroke={color} strokeWidth={strokeWidth} /><Path d="M8 6l1.2-2h5.6L16 6" stroke={color} strokeWidth={strokeWidth} strokeLinejoin="round" /><Circle cx="12" cy="13" r="3.4" stroke={color} strokeWidth={strokeWidth} /></Svg>;
    case 'gallery': return <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"><Rect x="3" y="4" width="18" height="16" rx="3" stroke={color} strokeWidth={strokeWidth} /><Circle cx="8.5" cy="9" r="1.3" fill={color} /><Path d="M5 16l4-4 3 3 3-2 4 3" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" /></Svg>;
    case 'phone': return <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"><Path d="M6.7 4.5h2.2c.5 0 1 .4 1.1.9l.6 3c.1.4-.1.9-.5 1.1l-1.8 1a14 14 0 006.3 6.3l1-1.8c.2-.4.7-.6 1.1-.5l3 .6c.5.1.9.6.9 1.1v2.2c0 .6-.5 1.2-1.2 1.2C10 21 3 14 5.5 5.7c0-.7.5-1.2 1.2-1.2z" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" /></Svg>;
    case 'mail': return <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"><Rect x="3" y="5" width="18" height="14" rx="3" stroke={color} strokeWidth={strokeWidth} /><Path d="M5 8l7 5 7-5" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" /></Svg>;
    case 'building': return <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"><Path d="M5 20V6.5A1.5 1.5 0 016.5 5h7A1.5 1.5 0 0115 6.5V20M9 20v-4h2v4M15 9h3a1 1 0 011 1v10h-4" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" /><Path d="M8 9h.01M12 9h.01M8 12h.01M12 12h.01" stroke={color} strokeWidth={strokeWidth + 0.4} strokeLinecap="round" /></Svg>;
    case 'link': return <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"><Path d="M10 14l4-4M8.5 15.5l-1.6 1.6a3 3 0 11-4.2-4.2L6 9.8a3 3 0 014.2 0M15.5 8.5l1.6-1.6a3 3 0 114.2 4.2L18 14.2a3 3 0 01-4.2 0" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" /></Svg>;
    case 'message': return <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"><Path d="M6 18l-2 2v-4.2A7 7 0 016 5h12a2 2 0 012 2v6a2 2 0 01-2 2H9.5L6 18z" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" /><Path d="M8.5 10.5h7M8.5 13.5h4.5" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" /></Svg>;
    case 'whatsapp': return <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"><Path d="M12 3.5a8.5 8.5 0 00-7.4 12.7L3.5 20.5l4.4-1.1A8.5 8.5 0 1012 3.5z" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" /><Path d="M9.5 8.6c.2-.5.4-.6.7-.6h.6c.2 0 .4.1.5.4l.7 1.8c.1.2 0 .5-.1.6l-.5.7c.5 1 1.3 1.9 2.3 2.4l.8-.5c.2-.1.4-.1.6 0l1.7.8c.2.1.4.3.3.5v.6c0 .3-.1.5-.5.7-.4.2-1 .3-1.6.2-1.4-.3-2.8-1.2-4-2.5-1.2-1.2-2-2.6-2.3-4-.1-.5 0-1.1.2-1.5z" fill={color} /></Svg>;
    case 'moon': return <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"><Path d="M19 14.5A7.5 7.5 0 019.5 5a8 8 0 1010 9.5z" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" /></Svg>;
    case 'warning': return <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"><Path d="M12 4l8 14H4l8-14z" stroke={color} strokeWidth={strokeWidth} strokeLinejoin="round" /><Path d="M12 9v4M12 16h.01" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" /></Svg>;
    case 'arrowLeft': return <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"><Path d="M15 6l-6 6 6 6M9 12h10" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" /></Svg>;
    case 'check': return <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"><Path d="M5 12.5l4.2 4.2L19 7" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" /></Svg>;
    case 'lock': return <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"><Rect x="5" y="11" width="14" height="10" rx="2.5" stroke={color} strokeWidth={strokeWidth} /><Path d="M8 11V8.5A4 4 0 0112 4.5a4 4 0 014 4V11" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" /><Circle cx="12" cy="16" r="1.3" fill={color} /></Svg>;
    case 'chevronRight': return <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"><Path d="M9 6l6 6-6 6" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" /></Svg>;
    case 'chevronDown': return <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"><Path d="M6 9l6 6 6-6" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" /></Svg>;
    case 'chevronUp': return <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"><Path d="M6 15l6-6 6 6" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" /></Svg>;
    case 'location': return <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"><Path d="M12 21s6-4.8 6-10a6 6 0 10-12 0c0 5.2 6 10 6 10z" stroke={color} strokeWidth={strokeWidth} strokeLinejoin="round" /><Circle cx="12" cy="11" r="2.2" stroke={color} strokeWidth={strokeWidth} /></Svg>;
    case 'search': return <Svg width={size} height={size} viewBox="0 0 24 24" fill="none"><Circle cx="11" cy="11" r="6.5" stroke={color} strokeWidth={strokeWidth} /><Path d="M16 16l4 4" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" /></Svg>;
    default: return null;
  }
}

export function PageHeader({ title, onBack }: { title: string; onBack: () => void }) {
  const { theme } = usePreferenceContext();
  return (
    <View style={[shared.header, { backgroundColor: theme.surface, borderBottomColor: theme.border, paddingTop: 0 }]}>
      <TouchableOpacity onPress={onBack} style={[shared.backBtn, { backgroundColor: theme.soft }]} activeOpacity={0.75}>
        <AppIcon name="arrowLeft" size={20} color={theme.textPrimary} />
      </TouchableOpacity>
      <Text style={[shared.title, { color: theme.textPrimary }]}>{title}</Text>
      <View style={{ width: 44 }} />
    </View>
  );
}

export function PrimaryBtn({ label, onPress }: { label: string; onPress: () => void }) {
  return <TouchableOpacity style={shared.primaryBtn} onPress={onPress} activeOpacity={0.85}><Text style={shared.primaryLabel}>{label}</Text></TouchableOpacity>;
}

export function EmptyState({ emoji, message }: { emoji: string; message: string }) {
  return <View style={shared.emptyWrap}><View style={shared.emptyCircle}><Text style={shared.emptyEmoji}>{emoji}</Text></View><Text style={shared.emptyText}>{message}</Text></View>;
}

export const shared = StyleSheet.create({
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, paddingTop: 12, paddingBottom: 10, borderBottomWidth: 1 },
  backBtn: { width: 36, height: 36, borderRadius: 10, alignItems: 'center', justifyContent: 'center', marginTop: 6 },
  title: { fontSize: 18, fontWeight: '800' },
  primaryBtn: { backgroundColor: C.primary, borderRadius: 16, height: 56, alignItems: 'center', justifyContent: 'center' },
  primaryLabel: { color: '#fff', fontSize: 16, fontWeight: '800', letterSpacing: 0.3 },
  emptyWrap: { alignItems: 'center', paddingVertical: 60 },
  emptyCircle: { width: 96, height: 96, borderRadius: 48, backgroundColor: C.primaryLight, alignItems: 'center', justifyContent: 'center', marginBottom: 16 },
  emptyEmoji: { fontSize: 40 },
  emptyText: { fontSize: 15, color: C.muted, fontWeight: '600', textAlign: 'center' },
});



